import test from 'node:test';
import assert from 'node:assert/strict';
import type { SceneDirection, TopicBrief } from '../types';
import { buildOmniPromptContext, compactIdentity, normalizeConstraintList } from './omniPromptContext';

const direction={number:1,start:0,end:6,duration:6,voiceover:'',silent:false,stage_id:'S01',state:'C',subject:'KJ-600',product_visual_state:'Complete',primary_action:'Taxis',supporting_motion:'Crew signals',environment_ref:'E1',environment_description:'Carrier deck',camera:{shot_scale:'medium-wide',lens:'35mm',angle:'low three-quarter',movement:'tracking',movement_speed:'slow'},lighting_and_material:'Daylight grey paint',continuity_from_previous:'None',transition_to_next:'Cut',required_visible_features:['rotodome'],forbidden_elements:['Jet engines','Weapons'],beat_id:'B1',reference_asset_ids:['R1']} satisfies SceneDirection;
const topic={topic:{title:'KJ-600',category:'aircraft'},global_visual_constants:'',environments:[],visual_lock:'Compact high-wing twin-turboprop | circular dorsal rotodome | exactly four vertical tail surfaces',product_identity_lock:{core_geometry:'high wing and four-fin tail',surface_finish:'naval grey',markings:'restrained',scale_reference:'crew scale',distinctive_features:['two turboprops','rotodome'],must_remain_consistent_across_all_scenes:true},visual_exclusions:'Northrop Grumman E-2 Hawkeye, Jet engines',negative_prompt_global:['Weapons','Readable text']} as TopicBrief;

test('normalizes nested constraints and identity without object coercion',()=>{assert.deepEqual(normalizeConstraintList(['Jet engines',['Weapons','jet engines'],'Northrop Grumman E-2']),['Jet engines','Weapons','Northrop Grumman E-2']);assert.doesNotMatch(compactIdentity(topic),/\[object Object\]/);});

test('Omni context keeps complete applicable evidence and omits unrelated handoff records',()=>{
  const handoff={schema:{name:'Handoff'},product:{official_name:'KJ-600'},dimensions_and_proportions:{overall_length:30},global_prompt_rules:{one_primary_action:true},production_stages:[{stage_id:'S01',environment_id:'E1',geometry_control:{primary_geometry_module_id:'M1'},visual_evidence:{reference_asset_ids:['R1']}},{stage_id:'S99',environment_id:'E99',geometry_control:{primary_geometry_module_id:'M99'},visual_evidence:{reference_asset_ids:['R99']}}],environments:[{environment_id:'E1'},{environment_id:'E99'}],geometry_modules:[{module_id:'M1'},{module_id:'M99'}],reference_assets:[{asset_id:'R1',identity:'KJ-600',configuration:'carrier AEW',production_state:'complete',viewpoint:'rear',visible_geometry_features:['four-fin tail'],allowed_usage:['identity'],forbidden_usage:['internal layout'],facility_status:'unassigned',confidence:'HIGH'},{asset_id:'R99',identity:'unrelated'}],visual_story_plan:{chapters:[{visual_beats:[{beat_id:'B1',reference_asset_ids:['R1']},{beat_id:'B99',reference_asset_ids:['R99']}]}]},stage_transitions:[{from_stage_id:'S00',to_stage_id:'S01'},{from_stage_id:'S01',to_stage_id:'S02'},{from_stage_id:'S98',to_stage_id:'S99'}]};
  const context:any=buildOmniPromptContext({...topic,_production_handoff:handoff} as any,[direction]),focused=context.authoritative_production_handoff;
  assert.equal(context.target_profile,'omni-flash');assert.deepEqual(focused.production_stages.map((item:any)=>item.stage_id),['S01']);assert.deepEqual(focused.environments.map((item:any)=>item.environment_id),['E1']);assert.deepEqual(focused.geometry_modules.map((item:any)=>item.module_id),['M1']);assert.deepEqual(focused.reference_assets.map((item:any)=>item.asset_id),['R1']);assert.deepEqual(focused.reference_assets[0],handoff.reference_assets[0]);assert.equal(focused.stage_transitions.length,2);assert.equal(focused.product.official_name,'KJ-600');
});
