import type { PlannedScene, SceneDirection } from '../types';

export const ALIGNMENT_INSTRUCTION_VERSION='alignment-v4-cinematic-only';
export const DIRECTION_INSTRUCTION_VERSION='direction-v4-cinematic-only';
export const PROMPT_INSTRUCTION_VERSION='prompt-v4-cinematic-only';
export const PROMPT_COMPILER_VERSION='compiler-v4-cinematic-only';

const operationalFamilies=new Set(['OPERATIONAL_CONTEXT','DYNAMIC_TESTING','ENVIRONMENTAL_TESTING','DELIVERY_AND_ROLLOUT','HERO_PRODUCT']);
const manufacturingFamilies=new Set(['ASSEMBLY_PROCESS','COMPONENT_MACRO','TOOL_LEVEL_DETAIL','WORKER_POV','MACHINERY_ACTION','QUALITY_CONTROL','MEASUREMENT_AND_CALIBRATION','MATERIAL_FLOW','COMPONENT_LOGISTICS','FACTORY_INTERIOR_WIDE','STATIC_GROUND_TEST']);

export interface InstructionFlags {aviation:boolean;operational:boolean;manufacturing:boolean;references:boolean;continuity:boolean;}
export function instructionFlags(items:Array<PlannedScene|SceneDirection>,productText=''):InstructionFlags{
  const text=`${productText} ${items.map(item=>`${item.visual_family||''} ${item.showdown_role||''} ${item.camera_platform||''} ${(item as SceneDirection).subject||''} ${(item as SceneDirection).primary_action||''}`).join(' ')}`;
  return {aviation:items.some(item=>Boolean(item.showdown_role||item.camera_platform))||/aircraft|airplane|fighter|jet|rotorcraft|helicopter|uav|uas|drone/i.test(text),operational:items.some(item=>operationalFamilies.has(String(item.visual_family))),manufacturing:items.some(item=>manufacturingFamilies.has(String(item.visual_family))),references:items.some(item=>(item.reference_asset_ids||[]).length>0),continuity:items.some(item=>((item as PlannedScene).continuity_requirements||[]).length>0||Boolean((item as SceneDirection).continuity_from_previous||(item as SceneDirection).transition_to_next))};
}

const alignmentCore=`Validate the visual meaning of each adjacent VO group. Choose ENGINE_BEAT only when one supplied cinematic candidate visibly complements the spoken idea without changing lifecycle stage, product identity, facility truth, or factual claim. Manufacturing narration must never select completed-product operational footage; deployed or operational narration must never select fabrication or unfinished factory work. All output is photographic, physical, cinematic, and evidence-led. For abstract narration, choose externally visible component detail, inspection, measurement, logistics, testing, facility context, atmosphere, or verified reference coverage; narration may carry meaning that cannot be shown literally. Never request technical graphics, diagrams, schematics, maps, vector animation, overlays, arrows, labels, fake UI, or invented internal mechanisms. Otherwise choose VO_FALLBACK with beat_id null and write one concrete, safe, camera-visible complementary claim grounded in supplied evidence. For a subscribe, follow, channel, or next-episode closing line, choose a safe product-context closing hero or payoff visual and never depict interface text. Return every supplied group exactly once. Confidence is 0 to 1. Deterministic cinematic balancing remains authoritative after this semantic decision.`;
export const composeAlignmentInstruction=(correctionFeedback?:string)=>[alignmentCore,correctionFeedback?`Correct only the supplied failed groups. Previous deterministic failures: ${correctionFeedback}.`:``].filter(Boolean).join(' ');

const directionCore=`You direct concise cinematic documentary scenes. Return one object per supplied planned scene and copy each scene number exactly. Return creative direction fields only; never return or change plan metadata, state, timing, or voiceover. Assigned beat, cinematic family, visibility, lifecycle state, stage, physical environment, required features, forbidden elements, and reference IDs are authoritative. Use photographic physical coverage that complements the exact narration; abstract meaning does not need literal visualization. Every clip is one continuous shot across its supplied generation duration with a physical opening, one primary supported motion, visible midpoint progression, synchronized atmospheric response, one achievable camera, and a settled ending. Preserve product identity, counts, scale, geometry, chronology, lifecycle state, configuration, and evidence limits. Product visibility is strict: NONE omits the product; DETAIL_ONLY remains module-scoped; PARTIAL preserves present and absent components; FULL preserves canonical identity. Never invent components, proprietary internals, hidden mechanisms, unsupported physical processes, future-stage components, readable text, labels, logos, maps, diagrams, schematics, vector overlays, floating arrows, precise generated data, exact events, or identifiable locations.`;
const directionContinuity=`Adjacent scenes assigned to the same beat or family form one sequence. Preserve subject, location, lifecycle state, product configuration, causal continuity, and unresolved transitions while advancing the visible action. Vary framing only when it improves narration; never change family, environment, or storyline merely for variety.`;
const directionReference=`Reference assets are Engine-researched evidence. Use their identity, configuration, production state, viewpoint, visible geometry, allowed usage, forbidden usage, facility status, and confidence exactly as supplied. Do not browse or reinterpret URLs and never broaden an allowed claim.`;
const directionManufacturing=`Manufacturing narration must remain at its assigned stage and facility truth. Never substitute deployed-product footage for manufacturing narration, a factory aerial for component narration, or a graphic for an assigned physical process.`;
const directionOperational=`For operational, dynamic-testing, environmental-testing, delivery, rollout, or hero footage, show the exact completed product performing one physically plausible defining function. Preserve its starting state, propulsion or control behavior, environmental response, and stable ending configuration. Never add combat, weapon discharge, explosions, impossible maneuvers, invented markings, or configuration changes.`;
const directionAviation=`Aviation roles form a controlled arc: anticipation and ground reveal establish scale; human scale and preparation show restrained professional readiness; departure progresses credibly into release; airborne establishment shows stable flight; performance pass uses one readable maneuver; cockpit immersion communicates forces through operator restraint, horizon, reflection, and vibration; environmental spectacle uses only physically caused vapor, cloud, heat haze, dust, spray, airflow, or downwash; operational reset returns to grounded preparation; second peak materially increases at least two supported intensity dimensions; controlled return settles through approach, landing, taxi, or subdued movement. Use the supplied physically credible camera platform. Preserve forward momentum, coordinated turns, plausible climb or descent, stable subject scale, and one configuration. Never use a camera that passes through the product or accelerates independently of its filming platform.`;
export function composeDirectionInstruction(items:Array<PlannedScene|SceneDirection>,productText='',correctionFeedback?:string):string{
  const flags=instructionFlags(items,productText),modules=[directionCore];
  if(flags.continuity)modules.push(directionContinuity);if(flags.references)modules.push(directionReference);if(flags.manufacturing)modules.push(directionManufacturing);if(flags.operational)modules.push(directionOperational);if(flags.aviation)modules.push(directionAviation);
  if(correctionFeedback)modules.push(`Correct only the supplied failed scenes. The reported deterministic failures are: ${correctionFeedback}. Preserve every valid neighboring result; return each failed scene exactly once.`);
  return modules.join(' ');
}

const promptCore=`Return one structured Omni Flash enhancement for every supplied cinematic live-action scene and copy each scene number exactly. Return only cinematography, subject, environment, style_lighting, and exclusions. The application deterministically supplies temporal action, product state, sound, duration, continuity metadata, stock keywords, identity guards, and final compilation, so do not repeat or rewrite them. Improve photographic staging, physical environmental specificity, lens behavior, material response, atmosphere, scale, and natural scene coherence. Use one primary supported action and one coherent camera. Treat the handoff and scene direction as authoritative; preserve counts, state, geometry, chronology, continuity, configuration, facility truth, evidence limits, and media restrictions. Abstract narration may use complementary physical imagery and must not cause invented mechanisms. Never return voiceover, duration, headings, raw JSON, abstract overlays, readable generated text, labels, logos, maps, diagrams, schematics, vector lines, floating arrows, fake UI, precise data, proprietary internals, or future components.`;
const promptOperational=`For operational footage, preserve the supplied starting state and show one physically plausible maneuver or function, propulsion or control behavior, synchronized environmental response, one achievable camera, and a stable ending. Never add weapon discharge, explosions, active combat, impossible maneuvers, unverified stores, invented markings, or exact-event/location claims.`;
const promptAviation=`For aviation footage, use the supplied physically credible filming platform, stable scale and geometry, one continuous aerodynamically plausible action, environmental response caused by the aircraft, and a settled ending. The assigned showdown role controls narrative intensity and progression.`;
const promptReference=`Use only the supplied Engine-inspected reference observations and allowed usage. Preserve viewpoint, configuration, visible geometry, facility status, forbidden usage, and confidence limits; never broaden a claim.`;
export function composeOmniPromptInstruction(items:SceneDirection[],productText='',correctionFeedback?:string):string{
  const flags=instructionFlags(items,productText),modules=[promptCore];if(flags.references)modules.push(promptReference);if(flags.operational)modules.push(promptOperational);if(flags.aviation)modules.push(promptAviation);if(correctionFeedback)modules.push(`Correct only the supplied failed scenes using this scene-specific feedback: ${correctionFeedback}.`);return modules.join(' ');
}
