import assert from 'node:assert/strict';
import test from 'node:test';
import type { AppState, SceneDirection, T2VPrompt } from '../types';
import template from '../schemas/Modus_Visual_Production_Handoff_V2_Template.json';
import { normalizeProductionHandoff } from './productionTemplate';
import { createResumableProductionSession, createProductionSession } from './productionSession';
import { idleGenerationSession } from './generationSession';
import { validateProductionReadiness } from './setupValidation';
import { isReviewAvailable, isWorkflowStageComplete, lastDurableProductionPoint, pendingProductionPoint, prepareSceneRepair, projectWorkflowStage } from './workflowState';
import { buildDocumentaryScenePlan } from './scenePlanner';

const scenes=[{number:1,start:0,end:6,duration:6,text:'First scene',silent:false},{number:2,start:6,end:12,duration:6,text:'Second scene',silent:false}];
const topic=normalizeProductionHandoff(JSON.parse(JSON.stringify(template)));
const transcript={audioFileName:'voice.json',duration:12,language:'en' as const,languageProbability:1,model:'external',computeType:'external',text:'First scene Second scene',segments:[],words:[],sceneDurationSeconds:6,scenes,importedAt:'now'};
const base=():AppState=>({projectSchemaVersion:15,projectName:'Workflow',projectFormat:'standard-lifecycle',phase:1,topic,plannedScenes:[],sceneDirections:[],masterVoiceoverScript:transcript.text,voiceoverTranscription:transcript,visualPrompts:[],generationSession:idleGenerationSession()});
const direction=(number:number)=>({number,start:(number-1)*6,end:number*6,duration:6,generation_duration_seconds:6,voiceover:scenes[number-1].text,silent:false,stage_id:'STG_01',state:'A',subject:'Material',product_visual_state:'State A',primary_action:'Material moves',supporting_motion:'Fixture holds',environment_ref:'ENV_01',environment_description:'Factory',camera:{shot_scale:'MEDIUM',lens:'NORMAL',angle:'EYE_LEVEL',movement:'STATIC',movement_speed:'NONE'},lighting_and_material:'Neutral',continuity_from_previous:'Continue',transition_to_next:'Cut',required_visible_features:['material'],forbidden_elements:['finished product']} as SceneDirection);
const prompt=(number:number)=>({number,action_description:'Material moves',video_prompt:'Omni prompt',voiceover:scenes[number-1].text,stock_keywords:'material'} as T2VPrompt);

test('Setup becomes ready only with both validated inputs',()=>{const state=base();assert.equal(validateProductionReadiness({...state,voiceoverTranscription:null}).ready,false);assert.equal(validateProductionReadiness(state).ready,true);assert.equal(projectWorkflowStage(state),1);});
test('an interrupted durable project opens in Production',()=>{const state=base(),session=createProductionSession(scenes,[]);assert.equal(projectWorkflowStage({...state,phase:2,plannedScenes:[{number:1} as any],generationSession:{...session,status:'interrupted'}}),2);});
test('a completed durable project opens in Review & Export',()=>{const state=base(),directions=scenes.map((_,index)=>direction(index+1)),prompts=scenes.map((_,index)=>prompt(index+1)),session=createResumableProductionSession(scenes,[],directions,prompts);assert.equal(projectWorkflowStage({...state,phase:2,sceneDirections:directions,visualPrompts:prompts,generationSession:{...session,status:'complete'}}),3);});
test('warning-only production is a clean completion and opens Review',()=>{const state=base(),directions=scenes.map((_,index)=>direction(index+1)),prompts=scenes.map((_,index)=>prompt(index+1)),session=createResumableProductionSession(scenes,[],directions,prompts),complete={...state,sceneDirections:directions,visualPrompts:prompts,generationSession:{...session,status:'complete_with_warnings' as const,validationWarnings:[{sceneNumber:1,code:'SEMANTIC_NOTE',severity:'WARNING' as const,message:'Advisory'}]}};assert.equal(projectWorkflowStage(complete),3);assert.equal(isWorkflowStageComplete(complete,2),true);});
test('review-marked production is complete with warnings and opens Review & Export',()=>{const state=base(),directions=[direction(1),direction(2)],prompts=[prompt(1),prompt(2)],session=createResumableProductionSession(scenes,[],directions,prompts),reviewed={...state,phase:3 as const,sceneDirections:directions,visualPrompts:prompts,generationSession:{...session,status:'complete_with_warnings' as const,sceneReviews:[{sceneNumber:2,operation:'DIRECTION' as const,status:'NEEDS_REVIEW' as const,repairAttempted:true as const,validationCodes:['LIFECYCLE_CONTRADICTION'],message:'Best result preserved',findings:[],candidateSource:'CORRECTION' as const,updatedAt:'now'}]}};assert.equal(isReviewAvailable(reviewed),true);assert.equal(projectWorkflowStage(reviewed),3);assert.equal(isWorkflowStageComplete(reviewed,2),true);});
test('quota recovery describes the last saved and exact pending operation',()=>{const state=base(),directions=[direction(1),direction(2)],prompts=[prompt(1)],session=createResumableProductionSession(scenes,[],directions,prompts),paused={...state,phase:2 as const,sceneDirections:directions,visualPrompts:prompts,generationSession:{...session,status:'paused' as const,pauseReason:'quota' as const,operation:'GENERATING_PROMPTS' as const}};assert.equal(lastDurableProductionPoint(paused),'Scene 1 · Prompt generated');assert.match(pendingProductionPoint(paused),/Scene 2 · generating prompts/i);});
test('selective prompt repair preserves every direction and unrelated prompt',()=>{const state=base(),directions=[direction(1),direction(2)],prompts=[prompt(1),prompt(2)],next=prepareSceneRepair({...state,sceneDirections:directions,visualPrompts:prompts},2,'prompt');assert.deepEqual(next.sceneDirections.map(item=>item.number),[1,2]);assert.deepEqual(next.visualPrompts.map(item=>item.number),[1]);assert.equal(next.phase,2);});
test('explicit selective repair removes only the selected review marker',()=>{const state=base(),directions=[direction(1),direction(2)],prompts=[prompt(1),prompt(2)],generationSession={...createResumableProductionSession(scenes,[],directions,prompts),sceneReviews:[{sceneNumber:1,operation:'DIRECTION' as const,status:'NEEDS_REVIEW' as const,repairAttempted:true as const,validationCodes:['A'],message:'A',findings:[],candidateSource:'ORIGINAL' as const,updatedAt:'now'},{sceneNumber:2,operation:'PROMPT' as const,status:'NEEDS_REVIEW' as const,repairAttempted:true as const,validationCodes:['B'],message:'B',findings:[],candidateSource:'CORRECTION' as const,updatedAt:'now'}]},next=prepareSceneRepair({...state,sceneDirections:directions,visualPrompts:prompts,generationSession},2,'prompt');assert.deepEqual(next.generationSession.sceneReviews.map(item=>`${item.operation}:${item.sceneNumber}`),['DIRECTION:1']);});

test('explicit regeneration of completed legacy graphic output becomes cinematic',()=>{
  const cinematic=buildDocumentaryScenePlan(topic,scenes)[0],graphicPlan={...cinematic,visual_family:'TECHNICAL_GRAPHIC' as const,visual_treatment:'MOTION_GRAPHIC_T2V' as const,graphic_spec:{graphic_subtype:'MECHANICAL_RELATIONSHIP' as const,visual_claim:'Hidden relationship',composition:'SINGLE_SUBJECT' as const,motion_pattern:'COMPONENT_TRANSLATION' as const,annotation_devices:['DIRECTIONAL_ARROWS' as const],palette_profile:'PREMIUM_TECHNICAL_VECTOR' as const,maximum_animated_elements:1 as const,transition_anchor:null,text_policy:'NO_GENERATED_TEXT' as const}},graphicDirection={...direction(1),...graphicPlan} as SceneDirection,state={...base(),phase:3 as const,plannedScenes:[graphicPlan],sceneDirections:[graphicDirection],visualPrompts:[prompt(1)]};
  const next=prepareSceneRepair(state,1,'prompt');
  assert.equal(next.visualPrompts.length,0);assert.equal(next.sceneDirections.length,0);assert.equal(next.plannedScenes[0].visual_treatment,'LIVE_ACTION_T2V');assert.equal(next.plannedScenes[0].graphic_spec,null);assert.ok(!['TECHNICAL_GRAPHIC','MAP_OR_SUPPLY_CHAIN'].includes(next.plannedScenes[0].visual_family));
});
