export type EvidenceConfidence = 'CONFIRMED'|'CORROBORATED'|'CREATOR_PROVIDED'|'ANALYST_INFERRED'|'UNKNOWN'|'HIGH'|'MEDIUM'|'LOW';
export type VisualFamily = 'FACTORY_AERIAL'|'FACTORY_EXTERIOR'|'FACILITY_APPROACH'|'FACTORY_INTERIOR_WIDE'|'MATERIAL_FLOW'|'COMPONENT_LOGISTICS'|'ASSEMBLY_PROCESS'|'COMPONENT_MACRO'|'TOOL_LEVEL_DETAIL'|'WORKER_POV'|'MACHINERY_ACTION'|'QUALITY_CONTROL'|'MEASUREMENT_AND_CALIBRATION'|'ENVIRONMENTAL_TESTING'|'STATIC_GROUND_TEST'|'DYNAMIC_TESTING'|'DELIVERY_AND_ROLLOUT'|'OPERATIONAL_CONTEXT'|'TECHNICAL_GRAPHIC'|'MAP_OR_SUPPLY_CHAIN'|'ARCHIVAL_REFERENCE'|'HERO_PRODUCT'|'CHAPTER_TRANSITION'|'ATMOSPHERIC_INTERSTITIAL';
export type StoryFunction = 'OPENING_HOOK'|'ESTABLISH_SCALE'|'ESTABLISH_LOCATION'|'INTRODUCE_COMPONENT'|'EXPLAIN_PROCESS'|'SHOW_MATERIAL_FLOW'|'SHOW_HUMAN_SCALE'|'SHOW_PRECISION'|'EXPLAIN_HIDDEN_SYSTEM'|'BRIDGE_STAGE'|'RESET_ATTENTION'|'PREVIEW_PAYOFF'|'DELIVER_PAYOFF'|'PROVIDE_CONTEXT'|'COMPARE_SYSTEMS'|'CONCLUDE_CHAPTER';
export type MediaRoute = 'GENERATED_T2V'|'REFERENCE_IMAGE_I2V'|'AUTHENTIC_VIDEO'|'EDITOR_NATIVE_GRAPHIC'|'REFERENCE_LOCKED_GRAPHIC'|'STATIC_IMAGE_WITH_MOTION'|'NO_VALID_ROUTE';
export type FacilityClaimStatus = 'EXACT_FACILITY_VERIFIED'|'FACILITY_TYPE_CORROBORATED'|'CONTEXTUAL_INDUSTRIAL_VISUAL'|'GENERIC_NON_IDENTIFYING_VISUAL'|'UNUSABLE';
export type ProductVisibility = 'NONE'|'PARTIAL'|'FULL'|'DETAIL_ONLY';
export type GenerationPermission = 'T2V_ALLOWED'|'REFERENCE_REQUIRED'|'EDITOR_ONLY'|'NOT_ALLOWED';
export type ProductStateCode = 'A'|'B'|'C';
export type SettingScope = 'INTERIOR'|'EXTERIOR'|'AERIAL'|'OUTDOOR_TEST'|'OPERATIONAL'|'GRAPHIC_SPACE';

export interface V2Measurement { value:number|null; unit:string; confidence:'CONFIRMED'|'CORROBORATED'|'CREATOR_PROVIDED'|'ANALYST_INFERRED'|'UNKNOWN'; }
export interface V2Product { official_name:string; exact_variant:string; product_class:string; manufacturer:string; aliases:string[]; overall_visual_description:string; immutable_identity_features:string[]; visually_similar_products_to_avoid:string[]; global_negative_constraints:string[]; }
export interface V2GeometryModule { module_id:string; module_name:string; required_visible_features:string[]; minimum_visible_anchor_count:number; forbidden_geometry_changes:string[]; likely_wrong_substitutions:string[]; }
export interface V2ReferenceAsset { asset_id:string; asset_type:'IMAGE'|'VIDEO'|'PDF'|'DIAGRAM'|'MAP'|'OTHER'; product_or_component:string; exact_variant_or_configuration:string; production_stage:string; view_angle:string; source_page_url:string; direct_media_url_or_file_reference:string; publisher_or_owner:string; date_or_event:string; visual_verification:'PASS'|'LIMITED'|'FAIL'; facility_claim_status:FacilityClaimStatus; exact_factory_verified:boolean; visible_geometry_features:string[]; allowed_usage:string[]; forbidden_usage:string[]; recommended_media_routes:MediaRoute[]; confidence:EvidenceConfidence; }
export interface V2Environment { environment_id:string; environment_name:string; setting_scope:SettingScope; facility_type:string; facility_claim_status:FacilityClaimStatus; exact_facility_name_if_verified:string; factory_zone:string; geographic_or_industrial_context:string; floor:string; walls:string; ceiling:string; lighting:string; exterior_features:string[]; aerial_features:string[]; machinery:string[]; jigs_and_supports:string[]; tools:string[]; worker_roles:string[]; worker_uniforms_and_ppe:string[]; scale_references:string[]; allowed_background_activity:string[]; forbidden_elements:string[]; }
export interface V2ProductState { overall_form:string; recognizable_as_final_product:boolean; orientation:string; support_method:string; surface_condition:string; markings_condition:string; interior_visibility:string; }
export interface V2GeometryControl { primary_geometry_module_id:string; secondary_geometry_module_ids:string[]; required_visible_anchors:string[]; minimum_visible_anchor_count:number; corrective_positive_geometry:string[]; likely_wrong_substitutions:string[]; negative_constraints:string[]; immutable_during_clip:string[]; forbidden_transformations:string[]; }
export interface V2StageAction { action_id:string; action_description:string; primary_subject:string; primary_action:string; allowed_minor_motion:string; required_tools_or_machinery:string[]; required_worker_roles:string[]; forbidden_actions:string[]; }
export interface V2CameraGuidance { preferred_views:string[]; safe_shot_scales:string[]; preferred_camera_movements:string[]; forbidden_camera_movements:string[]; high_risk_views:string[]; }
export interface V2StageVisualOpportunities { recommended_visual_families:VisualFamily[]; component_macro_opportunities:string[]; machinery_action_opportunities:string[]; worker_activity_opportunities:string[]; quality_control_opportunities:string[]; logistics_or_material_flow_opportunities:string[]; non_product_cutaway_opportunities:string[]; }
export interface V2VisualEvidence { confirmed_visual_details:string[]; analyst_inferred_visual_details:string[]; uncertain_visual_details:string[]; reference_asset_ids:string[]; }
export interface V2Continuity { previous_stage_end_state:string; current_stage_start_state:string; current_stage_end_state:string; next_stage_expected_state:string; features_that_must_remain_consistent:string[]; forbidden_regressions:string[]; }
export interface V2PromptConstraints { one_stable_product_state:boolean; one_primary_action:boolean; no_component_appears_before_installation:boolean; no_automatic_completion_of_product:boolean; no_geometry_morphing:boolean; no_readable_generated_text:boolean; must_repeat_exact_product_and_variant:boolean; must_repeat_present_and_absent_components:boolean; must_include_view_specific_geometry:boolean; }
export interface V2ProductionStage { stage_id:string; stage_number:number; stage_name:string; production_function:string; product_state_code:ProductStateCode; stage_visual_summary:string; environment_ids:string[]; product_state:V2ProductState; present_now:string[]; not_yet_installed:string[]; temporarily_exposed:string[]; open_interfaces:string[]; unfinished_edges_or_sections:string[]; geometry_control:V2GeometryControl; stage_actions:V2StageAction[]; camera_guidance:V2CameraGuidance; stage_visual_opportunities:V2StageVisualOpportunities; visual_evidence:V2VisualEvidence; continuity:V2Continuity; prompt_constraints:V2PromptConstraints; }
export interface V2StageTransition { from_stage_id:string; to_stage_id:string; components_added:string[]; components_enclosed_or_hidden:string[]; surface_changes:string[]; marking_changes:string[]; geometry_that_must_not_change:string[]; continuity_risks:string[]; recommended_bridge_visual_families:VisualFamily[]; }
export interface V2VisualBeat { beat_id:string; beat_order:number; beat_name:string; story_function:StoryFunction; visual_family:VisualFamily; narrative_purpose:string; semantic_alignment_terms:string[]; applicable_stage_ids:string[]; environment_ids:string[]; product_visibility:ProductVisibility; required_product_state_code:ProductStateCode|null; facility_claim_status:FacilityClaimStatus; reference_asset_ids:string[]; preferred_media_routes:MediaRoute[]; generation_permission:GenerationPermission; exact_factory_claim_allowed:boolean; preferred_shot_scales:string[]; preferred_camera_movements:string[]; minimum_usable_duration_seconds:number; preferred_duration_seconds:number; maximum_duration_seconds:number; must_show:string[]; must_not_show:string[]; continuity_requirements:string[]; negative_constraints:string[]; }
export interface V2Chapter { chapter_id:string; chapter_name:string; chapter_order:number; narrative_goal:string; chapter_question:string; chapter_payoff:string; opening_rehook_intent:string; applicable_production_stage_ids:string[]; required_visual_families:VisualFamily[]; optional_visual_families:VisualFamily[]; forbidden_visual_families:VisualFamily[]; visual_beats:V2VisualBeat[]; }
export interface V2RhythmPolicy { preferred_usable_scene_duration_seconds:{minimum:number;preferred:number;maximum:number}; maximum_consecutive_same_visual_family:number; maximum_consecutive_full_product_scenes:number; maximum_consecutive_same_environment_without_new_information:number; require_context_process_detail_cycle_when_supported:boolean; attention_reset_interval_seconds:{minimum:number;maximum:number}; minimum_meaningful_visual_families_per_60_seconds:number; avoid_repeated_camera_angle:boolean; avoid_repeated_camera_movement:boolean; avoid_decorative_visuals_without_narrative_purpose:boolean; }
export interface V2FactoryTruthPolicy { exact_factory_claim_requires_verified_reference:boolean; contextual_factory_must_not_be_presented_as_exact:boolean; generated_manufacturer_logos_forbidden:boolean; generated_readable_factory_text_forbidden:boolean; invented_facility_names_forbidden:boolean; }
export interface V2MediaRoutingPolicy { exact_product_geometry_prefers_reference_media:boolean; exact_markings_require_reference_lock:boolean; verified_events_prefer_authentic_media:boolean; maps_timelines_dimensions_and_diagrams_require_editor_graphics:boolean; generated_t2v_allowed_for_contextual_non_identifying_industrial_visuals:boolean; no_valid_route_must_be_flagged:boolean; }
export interface V2PercentRange { minimum:number; maximum:number; }
export interface V2VisualBalanceTargets { manufacturing_and_assembly_percent:V2PercentRange; factory_scale_and_logistics_percent:V2PercentRange; component_detail_and_quality_control_percent:V2PercentRange; testing_and_operational_context_percent:V2PercentRange; graphics_and_reference_media_percent:V2PercentRange; completed_product_hero_imagery_percent:V2PercentRange; targets_are_advisory_not_hard_quotas:boolean; }
export interface V2VisualStoryPlan { documentary_arc:{central_manufacturing_question:string;opening_visual_promise:string;promised_payoffs:string[];closing_visual_payoff:string}; chapters:V2Chapter[]; rhythm_policy:V2RhythmPolicy; factory_truth_policy:V2FactoryTruthPolicy; media_routing_policy:V2MediaRoutingPolicy; visual_balance_targets:V2VisualBalanceTargets; }
export interface VisualProductionHandoffV2 { schema:{name:'Modus Assembly Visual Production Handoff';version:'2.0.0';contract_type:'VISUAL_ONLY_ENGINE_TO_APP_HANDOFF'}; product:V2Product; dimensions_and_proportions:{overall_length:V2Measurement;overall_width_or_wingspan:V2Measurement;overall_height:V2Measurement;important_proportion_rules:string[];human_scale_reference:string}; geometry_modules:V2GeometryModule[]; reference_assets:V2ReferenceAsset[]; environments:V2Environment[]; production_stages:V2ProductionStage[]; stage_transitions:V2StageTransition[]; visual_story_plan:V2VisualStoryPlan; global_prompt_rules:Record<string,boolean|number|string>; }
export type VisualProductionHandoffV1 = Record<string,unknown> & { schema?:{name?:string;version?:string}; product?:Record<string,unknown>; production_stages?:unknown[] };
export type AnyVisualProductionHandoff = VisualProductionHandoffV1|VisualProductionHandoffV2;
