import { Dispatch, SetStateAction, useEffect, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, Copy, Download, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import type { AppState, T2VPromptProfile } from '../types';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { copyToClipboard } from '@/lib/utils';
import { formatTimestamp } from '../lib/timedTranscript';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { clampPromptPage, PROMPT_PAGE_SIZE, promptPageCount, promptPageItems } from '../lib/pagination';
import { Input } from '@/components/ui/input';
import { recompileOmniPrompts } from '../lib/omniPromptCompiler';
import { createResumableProductionSession } from '../lib/productionSession';

interface Props {state:AppState;setState:Dispatch<SetStateAction<AppState>>;}
const csvCell=(value:unknown)=>`"${String(value??'').replace(/"/g,'""')}"`;
const download=(name:string,text:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);};

export function Phase4Visuals({state,setState}:Props){
  const [promptPage,setPromptPage]=useState(1),[sceneJump,setSceneJump]=useState('');
  const directions=state.sceneDirections,ordered=[...state.visualPrompts].sort((a,b)=>a.number-b.number),pageCount=promptPageCount(ordered.length),pagePrompts=promptPageItems(ordered,promptPage),directionByNumber=new Map(directions.map(item=>[item.number,item]));
  const isComplete=directions.length>0&&ordered.length===directions.length&&state.generationSession.status==='complete';
  useEffect(()=>setPromptPage(page=>clampPromptPage(page,ordered.length)),[ordered.length]);
  const update=(number:number,field:'video_prompt'|'action_description'|'stock_keywords',value:string)=>setState(previous=>({...previous,visualPrompts:previous.visualPrompts.map(item=>item.number===number?{...item,[field]:value}:item)}));
  const allText=ordered.map(prompt=>`${prompt.number}: ${prompt.video_prompt}`).join('\n\n');
  const exportCsv=()=>download('t2v-prompts.csv',['profile,number,start,end,transcript_duration,generation_duration,chapter,beat,visual_family,story_function,visual_treatment,product_visibility,showdown_role,energy_level,camera_platform,graphic_subtype,graphic_claim,graphic_composition,graphic_motion,stage,state,action,voiceover,t2v_prompt,keywords,continuity,quality_flags,generation_source',...ordered.map(prompt=>{const direction=directionByNumber.get(prompt.number);return [state.t2vPromptProfile,prompt.number,direction?.start,direction?.end,direction?.duration,direction?.generation_duration_seconds,direction?.chapter_id,direction?.beat_id,direction?.visual_family,direction?.story_function,direction?.visual_treatment,direction?.product_visibility,direction?.showdown_role,direction?.energy_level,direction?.camera_platform,direction?.graphic_spec?.graphic_subtype,direction?.graphic_spec?.visual_claim,direction?.graphic_spec?.composition,direction?.graphic_spec?.motion_pattern,prompt.stage_id,prompt.state,prompt.action_description,prompt.voiceover,prompt.video_prompt,prompt.stock_keywords,prompt.continuity_notes,(prompt.quality_flags||[]).join('|'),prompt.generationSource].map(csvCell).join(',');})].join('\n'),'text/csv');
  const exportVo=()=>download('timestamped-vo.txt',directions.map(direction=>`[${formatTimestamp(direction.start)} - ${formatTimestamp(direction.end)}] Scene ${direction.number}${direction.silent?' [SILENT]':''}\n${direction.voiceover}`).join('\n\n'),'text/plain');
  const recompileAll=()=>{if(state.t2vPromptProfile!=='omni-flash'||!ordered.length)return;setState(previous=>({...previous,visualPrompts:recompileOmniPrompts(previous.visualPrompts,directions,previous.topic)}));toast.success(`Recompiled ${ordered.length} Omni prompt${ordered.length===1?'':'s'} locally. No API request was made.`);};
  const changeProfile=(value:T2VPromptProfile)=>setState(previous=>({...previous,phase:2,t2vPromptProfile:value,visualPrompts:[],demoScenes:[],demoSceneNumbers:[],demoState:'idle',generationSession:createResumableProductionSession(previous.voiceoverTranscription?.scenes||[],previous.plannedScenes,previous.sceneDirections,[])}));

  return <div className="phase-canvas space-y-6">
    <Button variant="link" className="p-0 text-muted-foreground" onClick={()=>setState(previous=>({...previous,phase:2}))}><ArrowLeft className="h-3 w-3 mr-1"/>Production status</Button>
    <div className="section-intro section-intro--amber"><div className="eyebrow text-amber-600 dark:text-amber-400">Review & Export</div><h2 className="text-xl font-bold mt-1">Review completed production prompts</h2><p className="text-sm text-muted-foreground mt-1">Inspect, refine, copy, and export the durably completed timestamped prompt set.</p></div>
    <div className="content-panel content-panel--amber p-4 sm:p-5 space-y-3"><label className="eyebrow">Google Flow target profile</label><Select value={state.t2vPromptProfile} onValueChange={value=>changeProfile(value as T2VPromptProfile)}><SelectTrigger className="max-w-md"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="omni-flash">Gemini Omni Flash</SelectItem><SelectItem value="veo-flow">Veo / Google Flow</SelectItem></SelectContent></Select><p className="text-[10px] text-muted-foreground">Changing profile invalidates only generated prompts and returns the project to Production. Technical graphics are compiled locally; live-action prompts retain model-assisted cinematic reasoning.</p></div>
    {isComplete&&<Badge className="bg-green-600/20 text-green-500 border-green-500/30">PRODUCTION COMPLETE · {directions.length} SCENES</Badge>}
    {ordered.length>0&&<div className="content-panel flex flex-wrap gap-2 p-3"><Button variant="outline" onClick={async()=>toast[await copyToClipboard(allText)?'success':'error'](`Copied ${ordered.length} prompt${ordered.length===1?'':'s'} in scene order.`)}><Copy className="h-4 w-4 mr-2"/>COPY ALL PROMPTS</Button>{state.t2vPromptProfile==='omni-flash'&&<Button variant="outline" onClick={recompileAll}><RefreshCw className="h-4 w-4 mr-2"/>RECOMPILE ALL LOCALLY</Button>}{isComplete&&<><Button variant="outline" onClick={exportCsv}><Download className="h-4 w-4 mr-2"/>CSV</Button><Button variant="outline" onClick={exportVo}><Download className="h-4 w-4 mr-2"/>TIMESTAMPED VO</Button></>}</div>}
    {ordered.length>0&&<div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border/60 bg-muted/30 p-3"><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={promptPage<=1} onClick={()=>setPromptPage(page=>page-1)}><ChevronLeft className="h-4 w-4"/>PREVIOUS</Button><span className="text-xs text-muted-foreground">Page {promptPage} of {pageCount} · {PROMPT_PAGE_SIZE} prompts maximum</span><Button variant="outline" size="sm" disabled={promptPage>=pageCount} onClick={()=>setPromptPage(page=>page+1)}>NEXT<ChevronRight className="h-4 w-4"/></Button></div><form className="flex items-center gap-2" onSubmit={event=>{event.preventDefault();const number=Number(sceneJump),index=ordered.findIndex(prompt=>prompt.number===number);if(index<0)return toast.error(`Scene ${sceneJump} is not available.`);setPromptPage(Math.floor(index/PROMPT_PAGE_SIZE)+1);}}><Input aria-label="Scene number" type="number" min={1} value={sceneJump} onChange={event=>setSceneJump(event.target.value)} placeholder="Scene #" className="h-9 w-24"/><Button type="submit" variant="outline" size="sm">GO</Button></form></div>}
    <div className="space-y-4">{pagePrompts.map(prompt=>{const direction=directionByNumber.get(prompt.number);return <div key={prompt.number} className="prompt-card border rounded-2xl p-4 sm:p-5 space-y-3"><div className="flex flex-wrap gap-2"><Badge>SCENE {prompt.number}</Badge><Badge variant="outline">{state.t2vPromptProfile==='omni-flash'?'Gemini Omni Flash':'Veo / Google Flow'}</Badge><Badge variant="outline">{formatTimestamp(direction?.start||0)}–{formatTimestamp(direction?.end||0)}</Badge><Badge variant="outline">{prompt.stage_id}</Badge><Badge variant="secondary">STATE {prompt.state}</Badge>{prompt.generationSource==='LOCAL_GRAPHIC'&&<Badge variant="outline">LOCAL GRAPHIC COMPILER</Badge>}</div><label className="text-[10px] text-muted-foreground">ACTION</label><Textarea value={prompt.action_description} onChange={event=>update(prompt.number,'action_description',event.target.value)} className="min-h-[65px]"/><label className="text-[10px] text-primary font-bold">T2V PROMPT</label><Textarea value={prompt.video_prompt} onChange={event=>update(prompt.number,'video_prompt',event.target.value)} className="min-h-[180px]"/><div className="bg-cyan-500/[0.06] border border-cyan-500/15 p-3.5 rounded-xl text-xs"><div className="text-[10px] text-cyan-700 dark:text-cyan-300 font-bold mb-1">EXACT IMPORTED VO {direction?.silent?'· SILENT WINDOW':''}</div>{prompt.voiceover||'[SILENT]'}</div><label className="text-[10px] text-muted-foreground">STOCK KEYWORDS</label><Textarea value={prompt.stock_keywords} onChange={event=>update(prompt.number,'stock_keywords',event.target.value)} className="min-h-[52px]"/></div>;})}</div>
  </div>;
}
