import { Dispatch, SetStateAction, useEffect, useState } from 'react';
import { AlertCircle, ArrowLeft, CheckCircle2, ChevronLeft, ChevronRight, Copy, Download, RefreshCw, ShieldCheck, Wrench } from 'lucide-react';
import { toast } from 'sonner';
import type { AppState } from '../types';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { copyToClipboard } from '@/lib/utils';
import { formatTimestamp } from '../lib/timedTranscript';
import { clampPromptPage, PROMPT_PAGE_SIZE, promptPageCount, promptPageItems } from '../lib/pagination';
import { Input } from '@/components/ui/input';
import { recompileOmniPrompts } from '../lib/omniPromptCompiler';
import { auditVisualBalance } from '../lib/visualBalance';
import { prepareSceneRepair } from '../lib/workflowState';

interface Props {state:AppState;setState:Dispatch<SetStateAction<AppState>>;}
const csvCell=(value:unknown)=>`"${String(value??'').replace(/"/g,'""')}"`;
const download=(name:string,text:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);};
const exportProject=(state:AppState)=>download(`${(state.projectName||'production').replace(/\s+/g,'_')}_AssemblyLine.json`,JSON.stringify(state,null,2),'application/json');

export function Phase4Visuals({state,setState}:Props){
  const [promptPage,setPromptPage]=useState(1),[sceneJump,setSceneJump]=useState('');
  const directions=state.sceneDirections,ordered=[...state.visualPrompts].sort((a,b)=>a.number-b.number),pageCount=promptPageCount(ordered.length),pagePrompts=promptPageItems(ordered,promptPage),directionByNumber=new Map(directions.map(item=>[item.number,item]));
  const total=state.voiceoverTranscription?.scenes.length||0,warnings=state.generationSession.validationWarnings||[],blockers=state.generationSession.deferredRepairs||[],isComplete=total>0&&directions.length===total&&ordered.length===total&&blockers.length===0&&(state.generationSession.status==='complete'||state.generationSession.status==='complete_with_warnings');
  const audit=auditVisualBalance(state.topic,state.voiceoverTranscription?.scenes||[],state.plannedScenes),familyEntries=Object.entries(audit.visualFamilyCounts).sort((a,b)=>b[1]-a[1]);
  useEffect(()=>setPromptPage(page=>clampPromptPage(page,ordered.length)),[ordered.length]);
  const update=(number:number,field:'video_prompt'|'action_description'|'stock_keywords',value:string)=>setState(previous=>({...previous,visualPrompts:previous.visualPrompts.map(item=>item.number===number?{...item,[field]:value}:item)}));
  const allText=ordered.map(prompt=>`${prompt.number}: ${prompt.video_prompt}`).join('\n\n');
  const exportCsv=()=>download('omni-prompts.csv',['number,start,end,transcript_duration,generation_duration,chapter,beat,visual_family,story_function,visual_treatment,product_visibility,showdown_role,energy_level,camera_platform,graphic_subtype,graphic_claim,graphic_composition,graphic_motion,stage,state,action,voiceover,omni_prompt,keywords,continuity,quality_flags,generation_source',...ordered.map(prompt=>{const direction=directionByNumber.get(prompt.number);return [prompt.number,direction?.start,direction?.end,direction?.duration,direction?.generation_duration_seconds,direction?.chapter_id,direction?.beat_id,direction?.visual_family,direction?.story_function,direction?.visual_treatment,direction?.product_visibility,direction?.showdown_role,direction?.energy_level,direction?.camera_platform,direction?.graphic_spec?.graphic_subtype,direction?.graphic_spec?.visual_claim,direction?.graphic_spec?.composition,direction?.graphic_spec?.motion_pattern,prompt.stage_id,prompt.state,prompt.action_description,prompt.voiceover,prompt.video_prompt,prompt.stock_keywords,prompt.continuity_notes,(prompt.quality_flags||[]).join('|'),prompt.generationSource].map(csvCell).join(',');})].join('\n'),'text/csv');
  const exportVo=()=>download('timestamped-vo.txt',directions.map(direction=>`[${formatTimestamp(direction.start)} - ${formatTimestamp(direction.end)}] Scene ${direction.number}${direction.silent?' [SILENT]':''}\n${direction.voiceover}`).join('\n\n'),'text/plain');
  const recompileAll=()=>{if(!ordered.length)return;setState(previous=>({...previous,visualPrompts:recompileOmniPrompts(previous.visualPrompts,directions,previous.topic)}));toast.success(`Recompiled ${ordered.length} Omni prompts locally. No API request was made.`);};
  const repairPrompt=(number:number)=>{if(!window.confirm(`Regenerate only Scene ${number}'s prompt? The current prompt will be removed; its direction and every other scene remain saved.`))return;setState(previous=>prepareSceneRepair(previous,number,'prompt'));toast.info(`Scene ${number} returned to Production for prompt repair.`);};
  return <div className="phase-canvas space-y-6">
    <Button variant="link" className="p-0 text-muted-foreground" onClick={()=>setState(previous=>({...previous,phase:2}))}><ArrowLeft className="mr-1 h-3 w-3"/>Production workspace</Button>
    <div className="section-intro section-intro--amber"><div className="eyebrow text-amber-600 dark:text-amber-400">Delivery workspace</div><h2 className="mt-1 text-xl font-bold">Review & Export</h2><p className="mt-1 text-sm text-muted-foreground">Inspect the globally audited Omni Flash prompt set, make selective repairs, and export production files.</p></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="metric-card"><div className="eyebrow">Scenes</div><strong>{total}</strong></div><div className="metric-card"><div className="eyebrow">Prompts</div><strong>{ordered.length}</strong></div><div className="metric-card"><div className="eyebrow">Graphics</div><strong>{audit.technicalGraphicPercentage}%</strong></div><div className="metric-card"><div className="eyebrow">Audit</div><strong className={isComplete?'text-emerald-500':'text-amber-500'}>{isComplete?'PASSED':'REVIEW'}</strong></div></div>
    <div className="content-panel content-panel--amber space-y-4 p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 font-bold"><ShieldCheck className={`h-4 w-4 ${isComplete?'text-emerald-500':'text-amber-500'}`}/>Global production audit</div><p className="mt-1 text-xs text-muted-foreground">{isComplete?`All durable batches contain directions, Omni prompts, and QA completion${warnings.length?' with advisory warnings':''}.`:blockers.length?`${blockers.length} isolated structured blocker${blockers.length===1?' prevents':'s prevent'} a clean completion; unaffected scenes remain usable and exportable.`:'This project still has incomplete durable production work.'}</p></div>{isComplete?<Badge className="w-fit bg-emerald-500/15 text-emerald-500"><CheckCircle2 className="mr-1 h-3 w-3"/>{warnings.length?'COMPLETE WITH WARNINGS':'PRODUCTION COMPLETE'}</Badge>:blockers.length>0&&<Badge variant="destructive" className="w-fit"><AlertCircle className="mr-1 h-3 w-3"/>REPAIRS DEFERRED</Badge>}</div><div className="flex flex-wrap gap-2">{familyEntries.map(([family,count])=><Badge key={family} variant="outline">{family.replaceAll('_',' ')} · {count}</Badge>)}</div>{blockers.length>0&&<div className="space-y-2 rounded-xl border border-red-500/25 bg-red-500/[0.05] p-3 text-xs"><div className="font-semibold text-red-400">Concrete blockers requiring scene-level repair</div>{blockers.map(item=><div key={`${item.operation}-${item.sceneNumber}`} className="rounded-lg bg-background/55 p-2"><strong>Scene {item.sceneNumber} · {item.operation} · {item.validationCode}</strong><div className="mt-1 text-muted-foreground">{item.lastError}</div>{item.finding?.structuredRuleSource&&<div className="mt-1 text-muted-foreground">Rule: {item.finding.structuredRuleSource} · Expected: {JSON.stringify(item.finding.expected)} · Actual: {JSON.stringify(item.finding.actual)}</div>}</div>)}</div>}{warnings.length>0&&<div className="rounded-xl border border-cyan-500/20 bg-cyan-500/[0.05] p-3 text-xs text-muted-foreground"><div className="mb-1 font-semibold text-cyan-500">Non-blocking validation warnings</div>{warnings.map(item=><div key={`${item.sceneNumber}-${item.code}`}>• Scene {item.sceneNumber}: {item.code}</div>)}</div>}{audit.warnings.length>0&&<div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs text-muted-foreground"><div className="mb-1 font-semibold text-amber-500">Advisory visual-rhythm notes</div>{audit.warnings.map(item=><div key={item}>• {item}</div>)}</div>}</div>
    {ordered.length>0&&<div className="content-panel flex flex-wrap gap-2 p-3"><Button variant="outline" onClick={async()=>toast[await copyToClipboard(allText)?'success':'error'](`Copied ${ordered.length} prompts in scene order.`)}><Copy className="mr-2 h-4 w-4"/>COPY ALL</Button><Button variant="outline" onClick={recompileAll}><RefreshCw className="mr-2 h-4 w-4"/>RECOMPILE LOCALLY</Button><Button variant="outline" onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>CSV</Button><Button variant="outline" onClick={exportVo}><Download className="mr-2 h-4 w-4"/>TIMESTAMPED VO</Button><Button variant="outline" onClick={()=>exportProject(state)}><Download className="mr-2 h-4 w-4"/>PROJECT JSON</Button></div>}
    {ordered.length>0&&<div className="flex flex-col gap-3 rounded-2xl border border-border/60 bg-muted/30 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={promptPage<=1} onClick={()=>setPromptPage(page=>page-1)}><ChevronLeft className="h-4 w-4"/>PREVIOUS</Button><span className="text-xs text-muted-foreground">Page {promptPage} of {pageCount} · {PROMPT_PAGE_SIZE} maximum</span><Button variant="outline" size="sm" disabled={promptPage>=pageCount} onClick={()=>setPromptPage(page=>page+1)}>NEXT<ChevronRight className="h-4 w-4"/></Button></div><form className="flex items-center gap-2" onSubmit={event=>{event.preventDefault();const number=Number(sceneJump),index=ordered.findIndex(prompt=>prompt.number===number);if(index<0)return toast.error(`Scene ${sceneJump} is not available.`);setPromptPage(Math.floor(index/PROMPT_PAGE_SIZE)+1);}}><Input aria-label="Scene number" type="number" min={1} value={sceneJump} onChange={event=>setSceneJump(event.target.value)} placeholder="Scene #" className="h-9 min-w-0 flex-1 sm:w-24 sm:flex-none"/><Button type="submit" variant="outline" size="sm">GO</Button></form></div>}
    <div className="space-y-4">{pagePrompts.map(prompt=>{const direction=directionByNumber.get(prompt.number);return <div key={prompt.number} className="prompt-card space-y-3 rounded-2xl border p-4 sm:p-5"><div className="flex flex-wrap items-center gap-2"><Badge>SCENE {prompt.number}</Badge><Badge variant="outline">OMNI FLASH</Badge><Badge variant="outline">{formatTimestamp(direction?.start||0)}–{formatTimestamp(direction?.end||0)}</Badge>{prompt.stage_id&&<Badge variant="outline">{prompt.stage_id}</Badge>}{prompt.state&&<Badge variant="secondary">STATE {prompt.state}</Badge>}{prompt.generationSource==='LOCAL_GRAPHIC'&&<Badge variant="outline">LOCAL GRAPHIC</Badge>}<Button size="sm" variant="ghost" className="ml-auto" onClick={()=>repairPrompt(prompt.number)}><Wrench className="mr-1 h-3 w-3"/>REPAIR PROMPT</Button></div><label className="text-[10px] text-muted-foreground">ACTION</label><Textarea value={prompt.action_description} onChange={event=>update(prompt.number,'action_description',event.target.value)} className="min-h-[65px]"/><label className="text-[10px] font-bold text-primary">OMNI VIDEO PROMPT</label><Textarea value={prompt.video_prompt} onChange={event=>update(prompt.number,'video_prompt',event.target.value)} className="min-h-[180px]"/><div className="rounded-xl border border-cyan-500/15 bg-cyan-500/[0.06] p-3.5 text-xs"><div className="mb-1 text-[10px] font-bold text-cyan-700 dark:text-cyan-300">EXACT IMPORTED VO {direction?.silent?'· SILENT WINDOW':''}</div>{prompt.voiceover||'[SILENT]'}</div><label className="text-[10px] text-muted-foreground">STOCK KEYWORDS</label><Textarea value={prompt.stock_keywords} onChange={event=>update(prompt.number,'stock_keywords',event.target.value)} className="min-h-[52px]"/></div>;})}</div>
  </div>;
}
