import { Dispatch, SetStateAction, useEffect, useState } from 'react';
import { AlertCircle, ArrowLeft, CheckCircle2, ChevronLeft, ChevronRight, Copy, Download, RefreshCw, ShieldCheck, Wrench } from 'lucide-react';
import { toast } from 'sonner';
import type { AppState } from '../types';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { copyToClipboard } from '@/lib/utils';
import { formatTimestamp } from '../lib/timedTranscript';
import { clampPromptPage, PROMPT_PAGE_SIZE, promptPageCount, promptPageItems } from '../lib/pagination';
import { Input } from '@/components/ui/input';
import { recompileOmniPrompts } from '../lib/omniPromptCompiler';
import { auditVisualBalance } from '../lib/visualBalance';
import { prepareSceneRepair } from '../lib/workflowState';
import { useSettings } from './SettingsContext';
import { AdvancedDetails } from './AdvancedDetails';

interface Props {state:AppState;setState:Dispatch<SetStateAction<AppState>>;}
const csvCell=(value:unknown)=>`"${String(value??'').replace(/"/g,'""')}"`;
const download=(name:string,text:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);};
const exportProject=(state:AppState)=>download(`${(state.projectName||'production').replace(/\s+/g,'_')}_AssemblyLine.json`,JSON.stringify(state,null,2),'application/json');

export function Phase4Visuals({state,setState}:Props){
  const {settings}=useSettings();
  const [promptPage,setPromptPage]=useState(1),[sceneJump,setSceneJump]=useState('');
  const directions=state.sceneDirections,ordered=[...state.visualPrompts].sort((a,b)=>a.number-b.number),pageCount=promptPageCount(ordered.length),pagePrompts=promptPageItems(ordered,promptPage),directionByNumber=new Map(directions.map(item=>[item.number,item]));
  const total=state.voiceoverTranscription?.scenes.length||0,warnings=state.generationSession.validationWarnings||[],blockers=state.generationSession.deferredRepairs||[],isComplete=total>0&&directions.length===total&&ordered.length===total&&blockers.length===0&&(state.generationSession.status==='complete'||state.generationSession.status==='complete_with_warnings');
  const audit=auditVisualBalance(state.topic,state.voiceoverTranscription?.scenes||[],state.plannedScenes),familyEntries=Object.entries(audit.visualFamilyCounts).sort((a,b)=>b[1]-a[1]);
  useEffect(()=>setPromptPage(page=>clampPromptPage(page,ordered.length)),[ordered.length]);
  const update=(number:number,field:'video_prompt'|'action_description'|'stock_keywords',value:string)=>setState(previous=>({...previous,visualPrompts:previous.visualPrompts.map(item=>item.number===number?{...item,[field]:value}:item)}));
  const allText=ordered.map(prompt=>`${prompt.number}: ${prompt.video_prompt}`).join('\n\n');
  const exportCsv=()=>download('omni-prompts.csv',['number,start,end,transcript_duration,generation_duration,chapter,beat,visual_family,story_function,visual_treatment,product_visibility,showdown_role,energy_level,camera_platform,graphic_subtype,graphic_claim,graphic_composition,graphic_motion,stage,state,action,voiceover,omni_prompt,keywords,continuity,quality_flags,generation_source',...ordered.map(prompt=>{const direction=directionByNumber.get(prompt.number);return [prompt.number,direction?.start,direction?.end,direction?.duration,direction?.generation_duration_seconds,direction?.chapter_id,direction?.beat_id,direction?.visual_family,direction?.story_function,direction?.visual_treatment,direction?.product_visibility,direction?.showdown_role,direction?.energy_level,direction?.camera_platform,direction?.graphic_spec?.graphic_subtype,direction?.graphic_spec?.visual_claim,direction?.graphic_spec?.composition,direction?.graphic_spec?.motion_pattern,prompt.stage_id,prompt.state,prompt.action_description,prompt.voiceover,prompt.video_prompt,prompt.stock_keywords,prompt.continuity_notes,(prompt.quality_flags||[]).join('|'),prompt.generationSource].map(csvCell).join(',');})].join('\n'),'text/csv');
  const exportVo=()=>download('timestamped-vo.txt',directions.map(direction=>`[${formatTimestamp(direction.start)} - ${formatTimestamp(direction.end)}] Scene ${direction.number}${direction.silent?' [SILENT]':''}\n${direction.voiceover}`).join('\n\n'),'text/plain');
  const recompileAll=()=>{if(!ordered.length)return;setState(previous=>({...previous,visualPrompts:recompileOmniPrompts(previous.visualPrompts,directions,previous.topic)}));toast.success(`Recompiled ${ordered.length} Omni prompts locally. No API request was made.`);};
  const repairPrompt=(number:number)=>{if(!window.confirm(`Regenerate only Scene ${number}'s prompt? The current prompt will be removed; its direction and every other scene remain saved.`))return;setState(previous=>prepareSceneRepair(previous,number,'prompt'));toast.info(`Scene ${number} returned to Production for prompt repair.`);};
  return <div className="phase-canvas space-y-6">
    <Button variant="link" className="p-0 text-muted-foreground" onClick={()=>setState(previous=>({...previous,phase:2}))}><ArrowLeft className="mr-1 h-3 w-3"/>Back to Production</Button>
    <div className="section-intro"><h2 className="text-lg font-semibold">Review & Export</h2><p className="mt-1 text-xs text-muted-foreground">Review only what needs attention, then export the finished production.</p></div>
    <div className="content-panel p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-base font-semibold"><ShieldCheck className={`h-4 w-4 ${isComplete?'text-emerald-500':'text-amber-500'}`}/>{isComplete?'Production complete':'Review required'}</div><p className="mt-1 text-xs text-muted-foreground">{total} scenes · {ordered.length} prompts{warnings.length?` · ${warnings.length} advisory warning${warnings.length===1?'':'s'}`:''}</p></div>{isComplete?<div className="status-success"><CheckCircle2 className="h-4 w-4"/>{warnings.length?'Complete with warnings':'QA passed'}</div>:<div className="status-warning"><AlertCircle className="h-4 w-4"/>{blockers.length} repair{blockers.length===1?'':'s'} needed</div>}</div></div>
    {ordered.length>0&&<div className="flex flex-wrap gap-2"><Button onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>Export prompts</Button><Button variant="outline" onClick={()=>exportProject(state)}><Download className="mr-2 h-4 w-4"/>Export project</Button><Button variant="outline" onClick={async()=>toast[await copyToClipboard(allText)?'success':'error'](`Copied ${ordered.length} prompts in scene order.`)}><Copy className="mr-2 h-4 w-4"/>Copy all</Button><Button variant="ghost" onClick={exportVo}><Download className="mr-2 h-4 w-4"/>Timestamped VO</Button>{settings.showProductionDiagnostics&&<Button variant="ghost" onClick={recompileAll}><RefreshCw className="mr-2 h-4 w-4"/>Recompile locally</Button>}</div>}
    {blockers.length>0&&<AdvancedDetails summary={`${blockers.length} scene repair${blockers.length===1?'':'s'} required`} className="border-destructive/30" defaultOpen><div className="space-y-2">{blockers.map(item=><div key={`${item.operation}-${item.sceneNumber}`} className="rounded-lg bg-destructive/[0.05] p-3 text-xs"><strong className="text-destructive">Scene {item.sceneNumber} needs {item.operation==='DIRECTION'?'direction':'prompt'} repair</strong><p className="mt-1 text-muted-foreground">Automatic repair could not safely complete this scene.</p>{settings.showProductionDiagnostics&&<div className="mt-2 font-mono text-[10px] text-muted-foreground">{item.validationCode} · {item.lastError}{item.finding?.structuredRuleSource?` · Rule ${item.finding.structuredRuleSource}`:''}</div>}</div>)}</div></AdvancedDetails>}
    {(warnings.length>0||audit.warnings.length>0)&&<AdvancedDetails summary={`${warnings.length+audit.warnings.length} advisory warning${warnings.length+audit.warnings.length===1?'':'s'}`}><div className="space-y-1 text-xs text-amber-500">{warnings.map(item=><div key={`${item.sceneNumber}-${item.code}`}>• Scene {item.sceneNumber}: Review suggested{settings.showProductionDiagnostics?` (${item.code})`:''}</div>)}{audit.warnings.map(item=><div key={item}>• {item}</div>)}</div></AdvancedDetails>}
    {settings.showProductionDiagnostics&&<AdvancedDetails summary="Production diagnostics"><div className="flex flex-wrap gap-2">{familyEntries.map(([family,count])=><Badge key={family} variant="outline">{family.replaceAll('_',' ')} · {count}</Badge>)}</div><div className="mt-3 text-xs text-muted-foreground">Graphics {audit.technicalGraphicPercentage}% · Status {state.generationSession.status} · Operation {state.generationSession.operation}</div></AdvancedDetails>}
    {ordered.length>0&&<div className="flex flex-col gap-3 rounded-2xl border border-border/60 bg-muted/30 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={promptPage<=1} onClick={()=>setPromptPage(page=>page-1)}><ChevronLeft className="h-4 w-4"/>PREVIOUS</Button><span className="text-xs text-muted-foreground">Page {promptPage} of {pageCount} · {PROMPT_PAGE_SIZE} maximum</span><Button variant="outline" size="sm" disabled={promptPage>=pageCount} onClick={()=>setPromptPage(page=>page+1)}>NEXT<ChevronRight className="h-4 w-4"/></Button></div><form className="flex items-center gap-2" onSubmit={event=>{event.preventDefault();const number=Number(sceneJump),index=ordered.findIndex(prompt=>prompt.number===number);if(index<0)return toast.error(`Scene ${sceneJump} is not available.`);setPromptPage(Math.floor(index/PROMPT_PAGE_SIZE)+1);}}><Input aria-label="Scene number" type="number" min={1} value={sceneJump} onChange={event=>setSceneJump(event.target.value)} placeholder="Scene #" className="h-9 min-w-0 flex-1 sm:w-24 sm:flex-none"/><Button type="submit" variant="outline" size="sm">GO</Button></form></div>}
    <div className="space-y-2">{pagePrompts.map(prompt=>{const direction=directionByNumber.get(prompt.number),warning=warnings.find(item=>item.sceneNumber===prompt.number);return <details key={prompt.number} className="prompt-row group rounded-xl border border-border/60 bg-background/35"><summary className="grid cursor-pointer list-none items-center gap-3 px-4 py-3 outline-none focus-visible:ring-2 focus-visible:ring-primary/40 sm:grid-cols-[95px_minmax(0,1fr)_auto]"><div><div className="text-xs font-semibold">Scene {prompt.number}</div><div className="mt-0.5 font-mono text-[10px] text-muted-foreground">{formatTimestamp(direction?.start||0)}–{formatTimestamp(direction?.end||0)}</div></div><p className="min-w-0 truncate text-xs text-foreground/90">{prompt.action_description}</p><span className={`flex items-center gap-1.5 text-xs font-medium ${warning?'text-amber-500':'text-emerald-500'}`}>{warning?<AlertCircle className="h-3.5 w-3.5"/>:<CheckCircle2 className="h-3.5 w-3.5"/>}{warning?'Review suggested':'Ready'}</span></summary><div className="space-y-3 border-t border-border/50 p-4"><div className="flex justify-end"><Button size="sm" variant="ghost" onClick={()=>repairPrompt(prompt.number)}><Wrench className="mr-1 h-3 w-3"/>Repair prompt</Button></div><label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Action</label><Textarea value={prompt.action_description} onChange={event=>update(prompt.number,'action_description',event.target.value)} className="min-h-[65px]"/><label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Final prompt</label><Textarea value={prompt.video_prompt} onChange={event=>update(prompt.number,'video_prompt',event.target.value)} className="min-h-[180px]"/><div className="rounded-lg border border-border/50 bg-muted/20 p-3 text-xs"><div className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Imported voiceover {direction?.silent?'· Silent window':''}</div>{prompt.voiceover||'[Silent]'}</div>{settings.showProductionDiagnostics&&<div className="space-y-2 rounded-lg bg-muted/20 p-3 font-mono text-[10px] text-muted-foreground"><div>Stage {prompt.stage_id||'—'} · State {prompt.state||'—'} · Source {prompt.generationSource||'—'}</div><div>Quality {(prompt.quality_flags||[]).join(', ')||'PASS'}</div><div className="break-all">Fingerprint {prompt.operationFingerprint||'—'}</div><Textarea value={prompt.stock_keywords} onChange={event=>update(prompt.number,'stock_keywords',event.target.value)} className="min-h-[52px]"/></div>}</div></details>;})}</div>
  </div>;
}
