import { Dispatch, SetStateAction, useEffect, useRef, useState } from 'react';
import { GoogleGenAI, Type } from '@google/genai';
import { AlertCircle, CheckCircle2, ChevronDown, Clock3, Download, KeyRound, Loader2, Pause, RefreshCw, ShieldCheck, Wrench } from 'lucide-react';
import { toast } from 'sonner';
import type { AppState, PersistedAlignmentSelection, PlannedScene, ProductionBatchState, ProjectCheckpointReason, SceneDirection, SceneReviewItem, TimedScene, ValidationFinding } from '../types';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Textarea } from '@/components/ui/textarea';
import { useSettings } from './SettingsContext';
import { buildDocumentaryScenePlan } from '../lib/scenePlanner';
import { applyVisualAlignments, buildAlignmentRequests } from '../lib/visualAlignment';
import { validateSceneDirections } from '../lib/sceneDirections';
import { auditVisualBalance } from '../lib/visualBalance';
import { createProductionSession, deriveProductionContext, isQuotaOrRateLimitError, mergeByNumber, mergeSceneReviews, mergeValidationWarnings, removeSceneReview, synchronizeProductionSession, updateProductionBatch } from '../lib/productionSession';
import { compileFallbackPrompt, partitionReusablePrompts, requestPromptAttempt } from '../lib/productionPrompt';
import { alignmentOperationFingerprint, directionOperationFingerprint, ItemFailure, partitionAlignmentResponse, partitionDirectionResponse, partitionReusableAlignmentSelections, partitionReusableDirections } from '../lib/productionApi';
import { buildFocusedProductionContext, focusedContextCharacterSavings } from '../lib/omniPromptContext';
import { composeAlignmentInstruction, composeDirectionInstruction } from '../lib/productionInstructions';
import { recordApiCall, recordFingerprintReuse, recordPartialAcceptance } from '../lib/apiDiagnostics';
import { batchStatusLabel, lastDurableProductionPoint, pendingProductionPoint, prepareBatchRedirect, prepareSceneRepair } from '../lib/workflowState';
import { formatTimestamp } from '../lib/timedTranscript';
import { stageChronologyFindings } from '../lib/validationModel';
import { productionOperationLabel } from '../lib/uiPresentation';
import { ProductionBatchList, ProductionHealthSummary } from './ProductionDetails';
import { clearResolvedEnvironmentRepairs } from '../lib/sceneContract';
import { buildFallbackDirection, chooseBestAvailable, sceneReviewFromFailure } from '../lib/sceneReview';
import { sceneReviewDependencyFingerprint } from '../lib/reviewFingerprint';

interface Props {state:AppState;setState:Dispatch<SetStateAction<AppState>>;commitProjectState:(state:AppState,checkpointReason?:ProjectCheckpointReason)=>Promise<AppState>;onOpenSettings:()=>void;}
const directionSchema={type:Type.ARRAY,items:{type:Type.OBJECT,required:['number','subject','product_visual_state','primary_action','supporting_motion','environment_description','camera','lighting_and_material','continuity_from_previous','transition_to_next','required_visible_features','forbidden_elements','temporal_action'],properties:{number:{type:Type.INTEGER},subject:{type:Type.STRING},product_visual_state:{type:Type.STRING},primary_action:{type:Type.STRING},supporting_motion:{type:Type.STRING},environment_description:{type:Type.STRING},camera:{type:Type.OBJECT,required:['shot_scale','lens','angle','movement','movement_speed'],properties:{shot_scale:{type:Type.STRING},lens:{type:Type.STRING},angle:{type:Type.STRING},movement:{type:Type.STRING},movement_speed:{type:Type.STRING}}},lighting_and_material:{type:Type.STRING},continuity_from_previous:{type:Type.STRING},transition_to_next:{type:Type.STRING},required_visible_features:{type:Type.ARRAY,items:{type:Type.STRING}},forbidden_elements:{type:Type.ARRAY,items:{type:Type.STRING}},temporal_action:{type:Type.OBJECT,required:['opening_state','primary_motion','physical_interaction','mid_shot_progression','ending_state'],properties:{opening_state:{type:Type.STRING},primary_motion:{type:Type.STRING},physical_interaction:{type:Type.STRING},mid_shot_progression:{type:Type.STRING},ending_state:{type:Type.STRING}}}}}};
const alignmentSchema={type:Type.ARRAY,items:{type:Type.OBJECT,required:['group_id','source','beat_id','confidence','visual_claim','graphic_required','graphic_scene_numbers'],properties:{group_id:{type:Type.STRING},source:{type:Type.STRING,enum:['ENGINE_BEAT','VO_FALLBACK']},beat_id:{type:Type.STRING,nullable:true},confidence:{type:Type.NUMBER},visual_claim:{type:Type.STRING},graphic_required:{type:Type.BOOLEAN},graphic_scene_numbers:{type:Type.ARRAY,items:{type:Type.INTEGER}}}}};

const parseResponse=(text:string|undefined):unknown=>{try{return JSON.parse(text||'[]');}catch{return null;}};
const issueRecord=(failures:ItemFailure[])=>Object.fromEntries(failures.map(item=>[item.id,item.issues]));
const feedback=(failures:ItemFailure[])=>failures.map(item=>`${item.id}: ${item.issues.join(', ')}`).join('; ');
const warningFromPrompt=(number:number,code:string):ValidationFinding=>({sceneNumber:number,code,severity:'WARNING',message:'Prompt QA reported an advisory concern; the prompt remains usable.',actual:code,repairHint:'Review selectively after production if desired.'});
const promptWarnings=(prompts:AppState['visualPrompts'])=>prompts.flatMap(prompt=>(prompt.quality_flags||[]).map(code=>warningFromPrompt(prompt.number,code)));
const productText=(state:AppState)=>`${(state.topic as any)?._production_handoff?.product?.product_class||''} ${state.topic?.topic?.product||''}`;
const exportProject=(state:AppState)=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${(state.projectName||'production').replace(/\s+/g,'_')}_resume.json`;anchor.click();URL.revokeObjectURL(url);};

class DurableCommitError extends Error {constructor(public readonly snapshot:AppState,cause:unknown){super(cause instanceof Error?cause.message:'Project storage failed after a paid result.');this.name='DurableCommitError';}}

export function ProductionPipeline({state,setState,commitProjectState,onOpenSettings}:Props){
  const {settings}=useSettings();
  const pauseRequested=useRef(false),started=useRef(false);
  const [running,setRunning]=useState(false),[statusText,setStatusText]=useState('Preparing production');
  const scenes=state.voiceoverTranscription?.scenes||[],session=state.generationSession,completed=state.visualPrompts.length,total=scenes.length;

  const persistStep=async(current:AppState,batchId:string,operation:Parameters<typeof updateProductionBatch>[2],data:Partial<AppState>={},batchPatch:Partial<ProductionBatchState>={},checkpoint=false)=>{
    let next={...current,...data,generationSession:updateProductionBatch(current.generationSession,batchId,operation,batchPatch)} as AppState;
    next={...next,generationSession:synchronizeProductionSession(next.generationSession,next)};
    try{return await commitProjectState(next,checkpoint?'batch':undefined);}catch(error){throw new DurableCommitError(next,error);}
  };
  const withWarnings=(current:AppState,warnings:ValidationFinding[])=>warnings.length?{...current,generationSession:{...current.generationSession,validationWarnings:mergeValidationWarnings(current.generationSession.validationWarnings,warnings)}}:current;
  const withReviews=(current:AppState,reviews:SceneReviewItem[])=>reviews.length?{...current,generationSession:{...current.generationSession,sceneReviews:mergeSceneReviews(current.generationSession.sceneReviews,reviews),deferredRepairs:[]}}:current;
  const clearReviews=(current:AppState,numbers:number[],operation:'DIRECTION'|'PROMPT')=>numbers.length?{...current,generationSession:{...current.generationSession,sceneReviews:numbers.reduce((items,number)=>removeSceneReview(items,number,operation),current.generationSession.sceneReviews)}}:current;
  const shouldPause=async(current:AppState)=>{if(!pauseRequested.current)return false;const paused={...current,generationSession:{...current.generationSession,status:'paused' as const,pauseReason:'user' as const,error:null}};await commitProjectState(paused);setStatusText('Paused safely after the last durable operation');return true;};

  const requestAlignments=async(ai:GoogleGenAI,current:AppState,requests:ReturnType<typeof buildAlignmentRequests>,batchPlan:PlannedScene[],context:ProductionBatchState['contextSnapshot'],correctionFailures:ItemFailure[]=[])=>{
    const focused=buildFocusedProductionContext(current.topic,batchPlan),fingerprints=new Map(requests.map(request=>[request.group_id,alignmentOperationFingerprint(settings.model,request,focused,context)]));
    recordApiCall('alignment',requests.length,{correction:Boolean(correctionFailures.length),estimatedInputCharactersAvoided:focusedContextCharacterSavings(current.topic,focused)});
    const response=await ai.models.generateContent({model:settings.model,contents:JSON.stringify({production_context:focused,persistent_context:context,groups:requests,correction_feedback:correctionFailures.length?issueRecord(correctionFailures):undefined}),config:{responseMimeType:'application/json',responseSchema:alignmentSchema,systemInstruction:composeAlignmentInstruction(correctionFailures.length?feedback(correctionFailures):undefined)}});
    const result=partitionAlignmentResponse(requests,parseResponse(response.text),fingerprints);recordPartialAcceptance(result.accepted.length,result.failed.length,Boolean(correctionFailures.length));return result;
  };

  const requestDirections=async(ai:GoogleGenAI,current:AppState,targetScenes:TimedScene[],targetPlan:PlannedScene[],context:ProductionBatchState['contextSnapshot'],correctionFailures:ItemFailure[]=[])=>{
    const focused=buildFocusedProductionContext(current.topic,targetPlan),fingerprints=new Map(targetScenes.map(scene=>{const plan=targetPlan.find(item=>item.number===scene.number)!;return [scene.number,directionOperationFingerprint(current,settings.model,scene,plan,context)];}));
    const prior=current.sceneDirections.filter(item=>item.number<(targetScenes[0]?.number||0)).at(-1)||null;
    const plannedScenes=targetPlan.map(plan=>({...plan,...targetScenes.find(item=>item.number===plan.number),voiceover:targetScenes.find(item=>item.number===plan.number)?.text}));
    const failedScenes=correctionFailures.map(failure=>({planned_scene:plannedScenes.find(item=>item.number===failure.number),rejected_direction:failure.candidate||null,validation_failures:failure.issues}));
    recordApiCall('direction',targetScenes.length,{correction:Boolean(correctionFailures.length),estimatedInputCharactersAvoided:focusedContextCharacterSavings(current.topic,focused)});
    const response=await ai.models.generateContent({model:settings.model,contents:JSON.stringify({production_context:focused,persistent_context:context,prior_scene:prior,...(correctionFailures.length?{failed_scenes:failedScenes}:{planned_scenes:plannedScenes})}),config:{responseMimeType:'application/json',responseSchema:directionSchema,systemInstruction:composeDirectionInstruction(targetPlan,productText(current),correctionFailures.length?feedback(correctionFailures):undefined)}});
    const result=partitionDirectionResponse(parseResponse(response.text),targetScenes,targetPlan,current.voiceoverTranscription!.sceneDurationSeconds,fingerprints,{topic:current.topic,afterRepair:Boolean(correctionFailures.length)});recordPartialAcceptance(result.accepted.length,result.failed.length,Boolean(correctionFailures.length));return result;
  };

  const run=async()=>{
    if(running||!state.topic||!state.voiceoverTranscription)return;
    let durable=state;
    const revalidated=clearResolvedEnvironmentRepairs(durable);
    if(revalidated.clearedSceneNumbers.length){
      durable=revalidated.state;
      const allOutputs=durable.visualPrompts.length===scenes.length&&durable.sceneDirections.length===scenes.length;
      if(allOutputs)durable={...durable,phase:3,generationSession:{...durable.generationSession,status:durable.generationSession.validationWarnings.length||durable.generationSession.sceneReviews.length?'complete_with_warnings':'complete',operation:'COMPLETE',pauseReason:null,error:null}};
      try{durable=await commitProjectState(durable,'manual');setState(durable);toast.success(`Cleared ${revalidated.clearedSceneNumbers.length} obsolete environment repair${revalidated.clearedSceneNumbers.length===1?'':'s'} locally. No API call was made.`);}
      catch(error){setState(durable);toast.error(error instanceof Error?error.message:'The corrected local state could not be saved. Retry before continuing.');return;}
      if(allOutputs)return;
    }
    const apiKey=settings.apiKey||process.env.GEMINI_API_KEY;if(!apiKey)return toast.error('Add a Gemini API key in Settings.');
    setRunning(true);pauseRequested.current=false;
    try{
      const ai=new GoogleGenAI({apiKey}),basePlan=buildDocumentaryScenePlan(state.topic,scenes);
      if(!durable.generationSession.batches.length)durable={...durable,generationSession:createProductionSession(scenes,basePlan)};
      durable=await commitProjectState({...durable,generationSession:{...durable.generationSession,status:'running',pauseReason:null,error:null,startedAt:durable.generationSession.startedAt||new Date().toISOString()}});
      for(const originalBatch of durable.generationSession.batches){
        let batch=durable.generationSession.batches.find(item=>item.id===originalBatch.id)!;
        if(batch.operation==='COMPLETE')continue;
        const numbers=new Set(batch.sceneNumbers),batchScenes=scenes.filter(item=>numbers.has(item.number));
        if(!batch.contextSnapshot){durable=await persistStep(durable,batch.id,batch.operation,{}, {contextSnapshot:deriveProductionContext(durable)},true);batch=durable.generationSession.batches.find(item=>item.id===batch.id)!;}
        const context=batch.contextSnapshot;

        let batchPlan=durable.plannedScenes.filter(item=>numbers.has(item.number));
        if(batchPlan.length!==batchScenes.length){setStatusText(`Batch ${batch.index}: planning scenes ${batch.sceneNumbers[0]}–${batch.sceneNumbers.at(-1)}`);durable=await persistStep(durable,batch.id,'PLANNING');batchPlan=basePlan.filter(item=>numbers.has(item.number));durable=await persistStep(durable,batch.id,'PLANNED',{plannedScenes:mergeByNumber(durable.plannedScenes,batchPlan)}, {},true);if(await shouldPause(durable))return;}
        batch=durable.generationSession.batches.find(item=>item.id===batch.id)!;batchPlan=durable.plannedScenes.filter(item=>numbers.has(item.number));

        const pastAlignment=['ALIGNED','DIRECTING','DIRECTION_CORRECTION','DIRECTED','GENERATING_PROMPTS','PROMPTS_GENERATED','PROMPT_CORRECTION','QA','COMPLETE'].includes(batch.operation);
        if(!pastAlignment){
          const requests=buildAlignmentRequests(durable.topic!,batchScenes,batchPlan),focused=buildFocusedProductionContext(durable.topic,batchPlan),reuse=partitionReusableAlignmentSelections(batch.alignmentSelections,requests,settings.model,focused,context),expected=reuse.fingerprints,reusable=reuse.reusable;
          if(reusable.length)recordFingerprintReuse(reusable.length);
          let selections=[...reusable],missing=reuse.missingRequests;
          if(missing.length){setStatusText(`Batch ${batch.index}: aligning ${missing.length} semantic group${missing.length===1?'':'s'}`);durable=await persistStep(durable,batch.id,'ALIGNING');const first=await requestAlignments(ai,durable,missing,batchPlan,context);selections=[...selections,...first.accepted];durable=await persistStep(durable,batch.id,'ALIGNING',{}, {alignmentSelections:selections,correctionIssues:issueRecord(first.failed)},true);if(await shouldPause(durable))return;
            if(first.failed.length){const failedIds=new Set(first.failed.map(item=>item.id)),retryRequests=missing.filter(request=>failedIds.has(request.group_id));setStatusText(`Batch ${batch.index}: correcting ${retryRequests.length} alignment group${retryRequests.length===1?'':'s'}`);const retry=await requestAlignments(ai,durable,retryRequests,batchPlan,context,first.failed),stillFailed=new Set(retry.failed.map(item=>item.id)),fallbacks:PersistedAlignmentSelection[]=retryRequests.filter(request=>stillFailed.has(request.group_id)).map(request=>({group_id:request.group_id,source:'VO_FALLBACK',beat_id:null,confidence:.35,visual_claim:request.voiceover.trim()||request.previous_context.trim()||request.next_context.trim()||'Safe product-context documentary visual',graphic_required:false,graphic_scene_numbers:[],operationFingerprint:expected.get(request.group_id)!}));selections=[...selections,...retry.accepted,...fallbacks];durable=withWarnings(durable,fallbacks.flatMap(selection=>(retryRequests.find(request=>request.group_id===selection.group_id)?.scene_numbers||[]).map(sceneNumber=>({sceneNumber,code:'ALIGNMENT_FALLBACK_AFTER_MALFORMED_RESPONSE',severity:'WARNING' as const,message:'A bounded alignment correction remained malformed, so the app used a deterministic VO-grounded fallback.',actual:selection.group_id,repairHint:'Optional review only; the fallback remains grounded in the supplied VO.'}))));durable=await persistStep(durable,batch.id,'ALIGNING',{}, {alignmentSelections:selections,correctionIssues:{}},true);if(await shouldPause(durable))return;}}
          const aligned=applyVisualAlignments(durable.topic!,batchScenes,batchPlan,requests,selections as PersistedAlignmentSelection[]).map(plan=>{const request=requests.find(item=>item.scene_numbers.includes(plan.number)),fingerprint=request?expected.get(request.group_id):undefined;return {...plan,alignmentFingerprint:fingerprint};});
          batchPlan=aligned;durable=await persistStep(durable,batch.id,'ALIGNED',{plannedScenes:mergeByNumber(durable.plannedScenes,aligned)},{alignmentSelections:selections,correctionIssues:{}},true);if(await shouldPause(durable))return;
        }
        batch=durable.generationSession.batches.find(item=>item.id===batch.id)!;batchPlan=durable.plannedScenes.filter(item=>numbers.has(item.number));

        const directionReuse=partitionReusableDirections(durable.sceneDirections.filter(item=>numbers.has(item.number)),batchScenes,batchPlan,durable,settings.model,context,{sceneReviews:durable.generationSession.sceneReviews}),reusableDirections=directionReuse.reusable,staleDirectionNumbers=new Set(directionReuse.staleSceneNumbers);
        durable=withWarnings(durable,directionReuse.warnings);
        if(reusableDirections.length)recordFingerprintReuse(reusableDirections.length);
        if(staleDirectionNumbers.size){durable={...durable,generationSession:{...durable.generationSession,sceneReviews:durable.generationSession.sceneReviews.filter(item=>!staleDirectionNumbers.has(item.sceneNumber)),validationWarnings:durable.generationSession.validationWarnings.filter(item=>!staleDirectionNumbers.has(item.sceneNumber))}};durable=await persistStep(durable,batch.id,'DIRECTING',{sceneDirections:durable.sceneDirections.filter(item=>!staleDirectionNumbers.has(item.number)),visualPrompts:durable.visualPrompts.filter(item=>!staleDirectionNumbers.has(item.number))},{directionCorrectionCandidates:[],promptCorrectionCandidates:[],directionCorrectionSceneNumbers:[],promptCorrectionSceneNumbers:[],correctionIssues:{}},true);}

        batch=durable.generationSession.batches.find(item=>item.id===batch.id)!;
        if(batch.directionCorrectionSceneNumbers.length){
          const pending=new Set(batch.directionCorrectionSceneNumbers),targetScenes=batchScenes.filter(item=>pending.has(item.number)),targetPlan=batchPlan.filter(item=>pending.has(item.number)),failures:ItemFailure[]=targetScenes.map(scene=>({id:String(scene.number),number:scene.number,issues:batch.correctionIssues[String(scene.number)]||['RETRY_REQUIRED'],candidate:batch.directionCorrectionCandidates.find(item=>item.number===scene.number)}));
          setStatusText(`Batch ${batch.index}: correcting ${targetScenes.length} direction${targetScenes.length===1?'':'s'}`);durable=await persistStep(durable,batch.id,'DIRECTION_CORRECTION');const retry=await requestDirections(ai,durable,targetScenes,targetPlan,context,failures);durable=withWarnings(durable,retry.warnings);
          const reviewed=retry.failed.map(failure=>{const scene=targetScenes.find(item=>item.number===failure.number)!,plan=targetPlan.find(item=>item.number===failure.number)!,original=failures.find(item=>item.number===failure.number),selected=chooseBestAvailable(original,failure,buildFallbackDirection(durable.topic,scene,plan,durable.voiceoverTranscription!.sceneDurationSeconds));return {direction:selected.candidate,review:sceneReviewFromFailure(scene.number,'DIRECTION',selected,'DIRECTION_QA_UNRESOLVED',sceneReviewDependencyFingerprint('DIRECTION',durable.topic,scene,plan))};});
          durable=clearReviews(durable,retry.accepted.map(item=>item.number),'DIRECTION');durable=withReviews(durable,reviewed.map(item=>item.review));durable=await persistStep(durable,batch.id,'DIRECTED',{sceneDirections:mergeByNumber(durable.sceneDirections,[...retry.accepted,...reviewed.map(item=>item.direction)])},{directionCorrectionCandidates:[],directionCorrectionSceneNumbers:[],correctionIssues:{}},true);if(await shouldPause(durable))return;
        }

        const directedNumbers=new Set(durable.sceneDirections.map(item=>item.number)),missingDirectionScenes=batchScenes.filter(item=>!directedNumbers.has(item.number));
        if(missingDirectionScenes.length){
          setStatusText(`Batch ${batch.index}: directing ${missingDirectionScenes.length} scene${missingDirectionScenes.length===1?'':'s'}`);durable=await persistStep(durable,batch.id,'DIRECTING');const missingPlan=batchPlan.filter(item=>missingDirectionScenes.some(scene=>scene.number===item.number)),first=await requestDirections(ai,durable,missingDirectionScenes,missingPlan,context);durable=withWarnings(durable,first.warnings);const remaining=first.failed.map(item=>item.number!);durable=await persistStep(durable,batch.id,remaining.length?'DIRECTION_CORRECTION':'DIRECTED',{sceneDirections:mergeByNumber(durable.sceneDirections,first.accepted)},{directionCorrectionCandidates:first.failed.flatMap(item=>item.candidate?[item.candidate]:[]),directionCorrectionSceneNumbers:remaining,correctionIssues:issueRecord(first.failed)},true);if(await shouldPause(durable))return;
          if(remaining.length){const failedSet=new Set(remaining),retryScenes=missingDirectionScenes.filter(item=>failedSet.has(item.number)),retryPlan=missingPlan.filter(item=>failedSet.has(item.number));setStatusText(`Batch ${batch.index}: correcting only ${retryScenes.length} failed direction${retryScenes.length===1?'':'s'}`);const retry=await requestDirections(ai,durable,retryScenes,retryPlan,context,first.failed);durable=withWarnings(durable,retry.warnings);const reviewed=retry.failed.map(failure=>{const scene=retryScenes.find(item=>item.number===failure.number)!,plan=retryPlan.find(item=>item.number===failure.number)!,original=first.failed.find(item=>item.number===failure.number),selected=chooseBestAvailable(original,failure,buildFallbackDirection(durable.topic,scene,plan,durable.voiceoverTranscription!.sceneDurationSeconds));return {direction:selected.candidate,review:sceneReviewFromFailure(scene.number,'DIRECTION',selected,'DIRECTION_QA_UNRESOLVED',sceneReviewDependencyFingerprint('DIRECTION',durable.topic,scene,plan))};});durable=clearReviews(durable,retry.accepted.map(item=>item.number),'DIRECTION');durable=withReviews(durable,reviewed.map(item=>item.review));durable=await persistStep(durable,batch.id,'DIRECTED',{sceneDirections:mergeByNumber(durable.sceneDirections,[...retry.accepted,...reviewed.map(item=>item.direction)])},{directionCorrectionCandidates:[],directionCorrectionSceneNumbers:[],correctionIssues:{}},true);if(await shouldPause(durable))return;}
        }
        durable=await persistStep(durable,batch.id,'DIRECTED',{}, {directionCorrectionCandidates:[],directionCorrectionSceneNumbers:[],correctionIssues:{}},true);
        batch=durable.generationSession.batches.find(item=>item.id===batch.id)!;const batchDirections=durable.sceneDirections.filter(item=>numbers.has(item.number));

        const promptReuse=partitionReusablePrompts(durable.visualPrompts.filter(item=>numbers.has(item.number)),batchDirections,durable,settings.model,context||undefined,{sceneReviews:durable.generationSession.sceneReviews}),reusablePrompts=promptReuse.reusable,stalePromptNumbers=new Set(promptReuse.staleSceneNumbers);
        durable=withWarnings(durable,promptWarnings(reusablePrompts));
        if(reusablePrompts.length)recordFingerprintReuse(reusablePrompts.length);
        if(stalePromptNumbers.size){durable={...durable,generationSession:{...durable.generationSession,sceneReviews:durable.generationSession.sceneReviews.filter(item=>item.operation!=='PROMPT'||!stalePromptNumbers.has(item.sceneNumber)),validationWarnings:durable.generationSession.validationWarnings.filter(item=>!stalePromptNumbers.has(item.sceneNumber))}};durable=await persistStep(durable,batch.id,'GENERATING_PROMPTS',{visualPrompts:durable.visualPrompts.filter(item=>!stalePromptNumbers.has(item.number))},{promptCorrectionCandidates:[],promptCorrectionSceneNumbers:[],correctionIssues:{}},true);}

        batch=durable.generationSession.batches.find(item=>item.id===batch.id)!;
        if(batch.promptCorrectionSceneNumbers.length){
          const pending=new Set(batch.promptCorrectionSceneNumbers),retryDirections=batchDirections.filter(item=>pending.has(item.number)),retryFeedback=retryDirections.map(item=>`Scene ${item.number}: ${(batch.correctionIssues[String(item.number)]||['RETRY_REQUIRED']).join(', ')}`).join('; '),originalFailures=retryDirections.map(direction=>({number:direction.number,issues:batch.correctionIssues[String(direction.number)]||['RETRY_REQUIRED'],candidate:batch.promptCorrectionCandidates.find(item=>item.number===direction.number)}));
          setStatusText(`Batch ${batch.index}: correcting only ${retryDirections.length} failed prompt${retryDirections.length===1?'':'s'}`);durable=await persistStep(durable,batch.id,'PROMPT_CORRECTION');const retry=await requestPromptAttempt(ai as any,settings.model,durable,retryDirections,retryFeedback,context||undefined);durable=withWarnings(durable,promptWarnings(retry.accepted));const reviewed=retry.failed.map(failure=>{const direction=retryDirections.find(item=>item.number===failure.number)!,scene=batchScenes.find(item=>item.number===failure.number)!,plan=batchPlan.find(item=>item.number===failure.number)!,original=originalFailures.find(item=>item.number===failure.number),selected=chooseBestAvailable(original,failure,compileFallbackPrompt(durable,direction,settings.model,context||undefined));return {prompt:selected.candidate,review:sceneReviewFromFailure(scene.number,'PROMPT',selected,'PROMPT_QA_UNRESOLVED',sceneReviewDependencyFingerprint('PROMPT',durable.topic,scene,plan,direction))};});durable=clearReviews(durable,retry.accepted.map(item=>item.number),'PROMPT');durable=withReviews(durable,reviewed.map(item=>item.review));durable=withWarnings(durable,promptWarnings(reviewed.map(item=>item.prompt)));durable=await persistStep(durable,batch.id,'PROMPTS_GENERATED',{visualPrompts:mergeByNumber(durable.visualPrompts,[...retry.accepted,...reviewed.map(item=>item.prompt)])},{promptCorrectionCandidates:[],promptCorrectionSceneNumbers:[],correctionIssues:{},correctionReason:null},true);if(await shouldPause(durable))return;
        }

        const promptNumbers=new Set(durable.visualPrompts.map(item=>item.number)),missingPromptDirections=batchDirections.filter(item=>!promptNumbers.has(item.number));
        if(missingPromptDirections.length){
          setStatusText(`Batch ${batch.index}: compiling/generating ${missingPromptDirections.length} prompt${missingPromptDirections.length===1?'':'s'}`);durable=await persistStep(durable,batch.id,'GENERATING_PROMPTS');const first=await requestPromptAttempt(ai as any,settings.model,durable,missingPromptDirections,undefined,context||undefined);durable=withWarnings(durable,promptWarnings(first.accepted));const remaining=first.failed.map(item=>item.number);durable=await persistStep(durable,batch.id,remaining.length?'PROMPT_CORRECTION':'PROMPTS_GENERATED',{visualPrompts:mergeByNumber(durable.visualPrompts,first.accepted)},{promptCorrectionCandidates:first.failed.flatMap(item=>item.candidate?[item.candidate]:[]),promptCorrectionSceneNumbers:remaining,correctionIssues:Object.fromEntries(first.failed.map(item=>[String(item.number),item.issues])),correctionReason:first.reason},true);if(await shouldPause(durable))return;
          if(remaining.length){const failedSet=new Set(remaining),retryDirections=missingPromptDirections.filter(item=>failedSet.has(item.number));setStatusText(`Batch ${batch.index}: correcting only ${retryDirections.length} failed prompt${retryDirections.length===1?'':'s'}`);const retry=await requestPromptAttempt(ai as any,settings.model,durable,retryDirections,first.reason||'Correct prompt QA failures',context||undefined);durable=withWarnings(durable,promptWarnings(retry.accepted));const reviewed=retry.failed.map(failure=>{const direction=retryDirections.find(item=>item.number===failure.number)!,scene=batchScenes.find(item=>item.number===failure.number)!,plan=batchPlan.find(item=>item.number===failure.number)!,original=first.failed.find(item=>item.number===failure.number),selected=chooseBestAvailable(original,failure,compileFallbackPrompt(durable,direction,settings.model,context||undefined));return {prompt:selected.candidate,review:sceneReviewFromFailure(scene.number,'PROMPT',selected,'PROMPT_QA_UNRESOLVED',sceneReviewDependencyFingerprint('PROMPT',durable.topic,scene,plan,direction))};});durable=clearReviews(durable,retry.accepted.map(item=>item.number),'PROMPT');durable=withReviews(durable,reviewed.map(item=>item.review));durable=withWarnings(durable,promptWarnings(reviewed.map(item=>item.prompt)));durable=await persistStep(durable,batch.id,'PROMPTS_GENERATED',{visualPrompts:mergeByNumber(durable.visualPrompts,[...retry.accepted,...reviewed.map(item=>item.prompt)])},{promptCorrectionCandidates:[],promptCorrectionSceneNumbers:[],correctionIssues:{},correctionReason:null},true);if(await shouldPause(durable))return;}
        }

        setStatusText(`Batch ${batch.index}: finalizing QA`);durable=await persistStep(durable,batch.id,'QA');durable=await persistStep(durable,batch.id,'COMPLETE',{}, {qaCompletedSceneNumbers:batch.sceneNumbers,directionCorrectionCandidates:[],promptCorrectionCandidates:[],directionCorrectionSceneNumbers:[],promptCorrectionSceneNumbers:[],correctionIssues:{},correctionReason:null},true);
      }
      const directionNumbers=new Set(durable.sceneDirections.map(item=>item.number)),promptNumbers=new Set(durable.visualPrompts.map(item=>item.number));
      if(scenes.some(scene=>!directionNumbers.has(scene.number)||!promptNumbers.has(scene.number)))throw new Error('Corrupted required project state: production finished a batch without a retained direction or prompt.');
      durable=withWarnings(durable,stageChronologyFindings([...durable.plannedScenes].sort((a,b)=>a.number-b.number),durable.topic));
      const directionErrors=validateSceneDirections(durable.sceneDirections,scenes,durable.plannedScenes,durable.voiceoverTranscription!.sceneDurationSeconds);if(directionErrors.length){const auditReviews=directionErrors.map(error=>{const sceneNumber=Number(error.match(/Scene\s+(\d+)/i)?.[1]||scenes[0]?.number||1),scene=scenes.find(item=>item.number===sceneNumber)!,plan=durable.plannedScenes.find(item=>item.number===sceneNumber)!;return {sceneNumber,operation:'DIRECTION' as const,status:'NEEDS_REVIEW' as const,repairAttempted:true as const,validationCodes:['FINAL_DIRECTION_AUDIT'],message:'Final local audit found a scene-level issue. The retained output remains available for review.',findings:[{sceneNumber,code:'FINAL_DIRECTION_AUDIT',severity:'BLOCKING_ERROR' as const,message:error,structuredRuleSource:'final scene direction audit',expected:'valid immutable direction',actual:error}],dependencyFingerprint:scene&&plan?sceneReviewDependencyFingerprint('DIRECTION',durable.topic,scene,plan):undefined,candidateSource:'ORIGINAL' as const,updatedAt:new Date().toISOString()};});durable=withReviews(durable,auditReviews);}
      const visualAudit=auditVisualBalance(durable.topic!,scenes,durable.plannedScenes);if(process.env.NODE_ENV!=='production'&&visualAudit.warnings.length)console.warn('Final production visual audit:',visualAudit);
      const reviewCount=new Set(durable.generationSession.sceneReviews.map(item=>item.sceneNumber)).size,nextStatus=reviewCount||durable.generationSession.validationWarnings.length?'complete_with_warnings' as const:'complete' as const;durable=await commitProjectState({...durable,phase:3,generationSession:{...synchronizeProductionSession(durable.generationSession,durable),status:nextStatus,operation:'COMPLETE',pauseReason:null,error:null,lastCommittedAt:new Date().toISOString(),deferredRepairs:[]}},'batch');toast.success(`Production complete. ${durable.visualPrompts.length} prompts are durably saved${reviewCount?`; ${reviewCount} scene${reviewCount===1?' needs':'s need'} review`:nextStatus==='complete_with_warnings'?' with advisory warnings':''}.`);
    }catch(error){
      const storage=error instanceof DurableCommitError,base=storage?error.snapshot:durable,quota=!storage&&isQuotaOrRateLimitError(error),message=error instanceof Error?error.message:'Production failed.',failed={...base,generationSession:{...synchronizeProductionSession(base.generationSession,base),status:quota||storage?'paused' as const:'failed' as const,pauseReason:storage?'storage' as const:quota?'quota' as const:'error' as const,error:message}};durable=failed;
      if(!storage){try{durable=await commitProjectState(failed,'batch');}catch{/* Existing storage banner handles persistence failure. */}}
      setState(durable);toast.error(storage?'Browser storage failed after an API result. The result remains in memory: retry storage or export before closing this page.':quota?'API credits or quota are exhausted. Accepted work is saved; export or resume with another profile/API key.':`Production paused: ${message}`);
    }finally{setRunning(false);started.current=false;}
  };

  useEffect(()=>{if(state.phase===2&&state.generationSession.status==='running'&&!started.current){started.current=true;void run();}},[state.phase,state.generationSession.status]);
  const resume=()=>setState(previous=>({...previous,generationSession:{...previous.generationSession,status:'running',pauseReason:null,error:null}}));
  const activeBatch=session.batches.find(batch=>batch.id===session.activeBatchId),activeDone=activeBatch?(session.operation.includes('PROMPT')?activeBatch.promptCompletedSceneNumbers.length:activeBatch.directionCompletedSceneNumbers.length):completed,activeTotal=activeBatch?.sceneNumbers.length||total;
  const health=auditVisualBalance(state.topic,scenes,state.plannedScenes),reviewCount=new Set(session.sceneReviews.map(item=>item.sceneNumber)).size,warningCount=session.validationWarnings.length,unresolved=session.correctionPendingSceneNumbers.length,cleanComplete=session.status==='complete'||session.status==='complete_with_warnings';
  const statusLabel=running?(warningCount||reviewCount?'RUNNING WITH WARNINGS':'RUNNING'):session.status==='complete_with_warnings'?'COMPLETE WITH REVIEW NOTES':session.status.replaceAll('_',' ').toUpperCase();
  const startRepair=async(number:number,kind:'prompt'|'direction')=>{const label=kind==='direction'?'direction and dependent prompt':'prompt';if(!window.confirm(`Regenerate Scene ${number}'s ${label}? Existing affected output will be removed. Every unrelated scene remains durably saved.`))return;const prepared=prepareSceneRepair(state,number,kind),next={...prepared,generationSession:{...prepared.generationSession,status:'running' as const,pauseReason:null,error:null}};await commitProjectState(next,'manual');};
  const redirectBatch=async(batchId:string)=>{const batch=session.batches.find(item=>item.id===batchId);if(!batch||!window.confirm(`Redirect Batch ${batch.index}, scenes ${batch.sceneNumbers[0]}–${batch.sceneNumbers.at(-1)}? Its directions and prompts will be removed and regenerated. Other batches remain saved.`))return;const prepared=prepareBatchRedirect(state,batchId),next={...prepared,generationSession:{...prepared.generationSession,status:'running' as const,pauseReason:null,error:null}};await commitProjectState(next,'manual');};
  const quotaPaused=session.pauseReason==='quota'||session.pauseReason==='rate_limit';
  return <div className="phase-canvas space-y-6">
    <div className="section-intro"><h2 className="text-lg font-semibold">Production</h2><p className="mt-1 text-xs text-muted-foreground">Progress is saved continuously. You can safely pause after the current operation.</p></div>
    <div className="content-panel space-y-5 p-4 sm:p-5">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="eyebrow">Production status</div><div className="mt-1 text-2xl font-extrabold">{completed} / {total} scenes complete</div><p className="mt-1 text-xs text-muted-foreground">{running?statusText:cleanComplete?'Final QA finished':session.status==='failed'?'A system or persistence operation needs attention':'Production is durably paused'}</p>{reviewCount>0&&<p className="mt-1 text-xs font-medium text-amber-500">{reviewCount} scene{reviewCount===1?' needs':'s need'} review · production {running?'continues automatically':'is complete'}</p>}</div><Badge variant={running?'default':session.status==='failed'?'destructive':'secondary'} className="w-fit">{running&&<Loader2 className="mr-1 h-3 w-3 animate-spin"/>}{statusLabel}</Badge></div>
      <Progress value={total?(completed/total)*100:0}/>
      {activeBatch&&<div className="grid gap-3 rounded-xl border border-border/60 bg-background/45 p-3 sm:grid-cols-[1fr_1fr_auto]"><div><div className="eyebrow">Current batch</div><strong className="text-sm">Batch {String(activeBatch.index).padStart(2,'0')} · Scenes {activeBatch.sceneNumbers[0]}–{activeBatch.sceneNumbers.at(-1)}</strong></div><div><div className="eyebrow">Now</div><strong className="text-sm">{productionOperationLabel(session.operation)}</strong></div><div><div className="eyebrow">Progress</div><strong className="text-sm">{activeDone} / {activeTotal}</strong></div></div>}
      {session.error&&!quotaPaused&&<div className="flex gap-2 rounded-xl border border-destructive/30 bg-destructive/[0.07] p-3 text-xs text-destructive"><AlertCircle className="h-4 w-4 shrink-0"/>{session.error}</div>}
      {(warningCount>0||reviewCount>0)&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/[0.06] p-3 text-xs"><strong>{reviewCount?`${reviewCount} scene${reviewCount===1?' needs':'s need'} review`:`${warningCount} advisory warning${warningCount===1?'':'s'}`}</strong><span className="ml-1 text-muted-foreground">Best available outputs are saved. These notes never stop later scenes, batches, completion, or export.</span></div>}
      <div className="flex flex-wrap gap-2">{running?<Button variant="outline" onClick={()=>{pauseRequested.current=true;setStatusText('Pause requested; saving the current accepted results first')}}><Pause className="mr-2 h-4 w-4"/>PAUSE SAFELY</Button>:!cleanComplete&&<Button onClick={resume}><RefreshCw className="mr-2 h-4 w-4"/>{session.status==='failed'?'RETRY SYSTEM FAILURE':'RESUME PRODUCTION'}</Button>}<Button variant="outline" onClick={()=>exportProject(state)}><Download className="mr-2 h-4 w-4"/>EXPORT PROJECT</Button></div>
    </div>
    {quotaPaused&&<div className="rounded-2xl border border-amber-500/35 bg-amber-500/[0.07] p-5 space-y-4"><div className="flex gap-3"><KeyRound className="h-5 w-5 shrink-0 text-amber-500"/><div><div className="font-bold text-amber-500">PRODUCTION PAUSED · API quota/credits unavailable</div><p className="mt-1 text-sm text-muted-foreground">No restart is needed. Every accepted result is durably saved.</p></div></div><div className="grid gap-2 text-xs sm:grid-cols-2"><div className="rounded-xl bg-background/60 p-3"><div className="eyebrow">Saved through</div><strong>{lastDurableProductionPoint(state)}</strong>{session.lastCommittedAt&&<div className="mt-1 text-muted-foreground">Committed {new Date(session.lastCommittedAt).toLocaleString()}</div>}</div><div className="rounded-xl bg-background/60 p-3"><div className="eyebrow">Pending</div><strong>{pendingProductionPoint(state)}</strong></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>exportProject(state)}><Download className="mr-2 h-4 w-4"/>EXPORT PROJECT</Button><Button variant="outline" onClick={onOpenSettings}><KeyRound className="mr-2 h-4 w-4"/>UPDATE API KEY</Button><Button onClick={resume}><RefreshCw className="mr-2 h-4 w-4"/>RESUME PRODUCTION</Button></div></div>}
    <ProductionHealthSummary families={Object.keys(health.visualFamilyCounts).length} graphics={health.technicalGraphicPercentage} longestRun={health.longestSameFamilyRun.length} prompts={completed} total={total} warnings={warningCount+health.warnings.length+unresolved} reviewCount={reviewCount}/>
    <ProductionBatchList state={state} running={running} showDiagnostics={settings.showProductionDiagnostics} onRepair={(number,kind)=>void startRepair(number,kind)} onRedirectBatch={batchId=>void redirectBatch(batchId)}/>
    {cleanComplete&&<div className={`flex items-center gap-2 text-sm ${reviewCount?'text-amber-500':'text-emerald-500'}`}>{reviewCount?<AlertCircle className="h-4 w-4"/>:<CheckCircle2 className="h-4 w-4"/>}All batches are complete and ready for Review & Export{reviewCount?`; ${reviewCount} scene${reviewCount===1?' has':'s have'} optional review notes`:warningCount?' with advisory warnings':''}.</div>}{running&&<div className="flex items-center gap-2 text-xs text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Each failed scene receives at most one automatic repair; unresolved output is preserved and production continues.</div>}
  </div>;
}
